import { createFateClient } from './__generated__/fate';

/**
 * Configured Fate client (native transport).
 *
 * `createFateClient` is generated by the `react-fate/vite` plugin from our
 * server module (app/fate/server.ts) — see app/fate/__generated__/fate.ts.
 * It wires the typed roots + an HTTP transport at our mounted endpoints.
 */
export const fateClient = createFateClient({
  url: '/api/fate',
  liveUrl: '/api/fate/live',
});

// Re-export the React hooks + provider for convenience.
export {
  FateClient as FateProvider,
  useView,
  useListView,
  useLiveView,
  useLiveListView,
  useRequest,
  view,
  mutation,
} from 'react-fate';
