import { createClient, type Client } from '@libsql/client';
import * as path from 'node:path';
import * as fs from 'node:fs';

/**
 * The contributions store (Show Detail Wiki, M0).
 *
 * This is the durable, user-writable half of the show-detail overlay model
 * (see sdk/docs/show-detail-wiki-plan.md). It is the source of truth for
 * everything humans author — pages, per-row overrides of scraped data, authored
 * blocks, append-only revision history, uploaded-media records, and stewardship.
 * It is NEVER regenerated by the nightly read-model emit; scraped facts and human
 * prose are merged at read time (`displayed = override ?? scraped`).
 *
 * Persistence (plan §3.1/§3.2, invariant I-7): in production this MUST live on the
 * Coolify persistent volume mounted at /data — the container FS is rebuilt on every
 * deploy, so a path inside the image would lose every contribution since the last
 * backup. Point CONTRIBUTIONS_DB_URL at file:/data/contributions.db in prod. The
 * write path must fail closed when the durable volume is missing (see
 * `durableStorageStatus` — enforced by write server-fns starting in M3, not here).
 *
 * Concurrency (plan §8.1, H-3): WAL + a busy_timeout so the single-writer /
 * many-reader shape (editor saves + append-only revision inserts + the off-peak
 * reconciler) doesn't throw SQLITE_BUSY. Write transactions are kept small.
 */

const repoRoot = process.cwd();
const sdkDir = path.resolve(repoRoot, 'sdk');

// Prod sets CONTRIBUTIONS_DB_URL=file:/data/contributions.db (durable volume).
// Dev falls back to a repo-local file for zero-config local editing.
const dbUrl =
  process.env.CONTRIBUTIONS_DB_URL ?? `file:${path.resolve(sdkDir, 'contributions.db')}`;

/** Strip the libsql `file:` scheme to a filesystem path (null for remote URLs). */
const filePathOf = (url: string): string | null =>
  url.startsWith('file:') ? url.slice('file:'.length) : null;

export type DurableStorageStatus = { ready: boolean; reason: string };

/**
 * Is the contributions DB sitting on durable storage we can write to (I-7)?
 *
 * Write server-fns call this and fail closed when it is not ready, rather than
 * persisting to an ephemeral container FS a redeploy will discard. Reads never
 * depend on this. Conservative + cheap: we only assert the DB's parent directory
 * exists and is writable. In prod that directory is /data, which only exists when
 * the persistent volume is actually mounted — a missing mount surfaces here as a
 * hard "not ready" instead of a silent data-loss bug.
 */
export const durableStorageStatus = (): DurableStorageStatus => {
  const filePath = filePathOf(dbUrl);
  if (!filePath) return { ready: true, reason: 'remote libsql url (durability delegated)' };
  const dir = path.dirname(filePath);
  try {
    if (!fs.existsSync(dir)) return { ready: false, reason: `storage dir missing: ${dir}` };
    fs.accessSync(dir, fs.constants.W_OK);
    return { ready: true, reason: `writable: ${dir}` };
  } catch {
    return { ready: false, reason: `storage dir not writable: ${dir}` };
  }
};

// Shared, long-lived client + once-per-process PRAGMA + DDL (mirrors media-cache.ts).
let sharedDb: Client | null = null;
let initialized: Promise<Client> | null = null;

const PRAGMAS = [
  'PRAGMA journal_mode=WAL', // one writer / many readers without SQLITE_BUSY storms
  'PRAGMA busy_timeout=5000', // wait up to 5s for a lock before erroring (H-3)
  'PRAGMA synchronous=NORMAL', // durable enough under WAL; faster small commits
  'PRAGMA foreign_keys=ON',
];

// One DDL statement per table/index. CREATE ... IF NOT EXISTS = safe to re-run.
// Schema mirrors plan §8. better-auth owns its own auth_* tables (added in M2).
const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS show_pages (
     page_id    TEXT PRIMARY KEY,
     corps_key  TEXT NOT NULL,
     season     TEXT NOT NULL,
     show_id    TEXT,                       -- soft pointer, re-resolved nightly
     status     TEXT NOT NULL DEFAULT 'active',  -- active | orphaned
     lock_level TEXT NOT NULL DEFAULT 'none',    -- none | trusted | mod
     created_at TEXT NOT NULL,
     updated_at TEXT NOT NULL,
     UNIQUE (corps_key, season)
   )`,
  `CREATE TABLE IF NOT EXISTS show_stewards (
     page_id    TEXT NOT NULL,
     user_id    TEXT NOT NULL,
     created_at TEXT NOT NULL,
     PRIMARY KEY (page_id, user_id)
   )`,
  // Per-row overlay for SEEDABLE pinned sections (repertoire/staff/movements/media).
  `CREATE TABLE IF NOT EXISTS show_block_overrides (
     override_id     TEXT PRIMARY KEY,
     page_id         TEXT NOT NULL,
     pinned_key      TEXT NOT NULL,          -- which seedable section
     natural_key     TEXT NOT NULL,          -- stable id of the scraped row (§5)
     state           TEXT NOT NULL,          -- edited | added | hidden
     content_json    TEXT,                   -- authored row value (null for 'hidden')
     source_hash     TEXT,                   -- scraped-row hash at override time (null for 'added')
     scrape_diverged INTEGER NOT NULL DEFAULT 0,
     position        INTEGER,
     updated_at      TEXT NOT NULL,
     updated_by      TEXT NOT NULL,
     UNIQUE (page_id, pinned_key, natural_key)
   )`,
  // AUTHORED-only pinned blocks (uniform/props/links/symbolism) + free-form blocks.
  `CREATE TABLE IF NOT EXISTS show_blocks (
     block_id     TEXT PRIMARY KEY,
     page_id      TEXT NOT NULL,
     kind         TEXT NOT NULL,             -- pinned | freeform
     pinned_key   TEXT,                       -- non-null iff kind='pinned'
     position     INTEGER NOT NULL,           -- freeform ordering
     content_json TEXT NOT NULL,
     updated_at   TEXT NOT NULL,
     updated_by   TEXT NOT NULL,
     UNIQUE (page_id, pinned_key)
   )`,
  `CREATE TABLE IF NOT EXISTS show_revisions (
     revision_id TEXT PRIMARY KEY,
     page_id     TEXT NOT NULL,
     target_kind TEXT NOT NULL,              -- override | block | page
     target_id   TEXT,
     author_id   TEXT NOT NULL,
     created_at  TEXT NOT NULL,
     op          TEXT NOT NULL,              -- create|edit|revert|reorder|add|hide|restore
     actor_role  TEXT NOT NULL,              -- role frozen at write time (§6.5)
     before_json TEXT,
     after_json  TEXT,
     summary     TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS show_media (
     media_id    TEXT PRIMARY KEY,
     page_id     TEXT NOT NULL,
     block_id    TEXT,                        -- block_id or override_id; nullable
     r2_key      TEXT NOT NULL,
     kind        TEXT NOT NULL,               -- image|cover|clip|embed
     width       INTEGER,
     height      INTEGER,
     alt         TEXT,
     attribution TEXT,
     uploaded_by TEXT NOT NULL,
     uploaded_at TEXT NOT NULL
   )`,
  // Citations / references (plan §18): page-scoped, deduped bibliography. Content
  // references these by citation_id; numbering is derived at render (I-16).
  `CREATE TABLE IF NOT EXISTS show_citations (
     citation_id    TEXT PRIMARY KEY,
     page_id        TEXT NOT NULL,
     url            TEXT,                       -- null for offline sources
     normalized_url TEXT,                       -- dedupe key
     title          TEXT,
     publisher      TEXT,
     type           TEXT NOT NULL DEFAULT 'other',
     quote          TEXT,
     accessed_at    TEXT,
     created_at     TEXT NOT NULL,
     created_by     TEXT NOT NULL,
     UNIQUE (page_id, normalized_url)
   )`,
  `CREATE INDEX IF NOT EXISTS idx_citations_page ON show_citations (page_id)`,
  `CREATE INDEX IF NOT EXISTS idx_overrides_page_key ON show_block_overrides (page_id, pinned_key)`,
  `CREATE INDEX IF NOT EXISTS idx_blocks_page ON show_blocks (page_id)`,
  `CREATE INDEX IF NOT EXISTS idx_revisions_page_time ON show_revisions (page_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_media_page ON show_media (page_id)`,
  `CREATE INDEX IF NOT EXISTS idx_stewards_user ON show_stewards (user_id)`,

  // ---------------------------------------------------------------------------
  // Fantasy DCI (docs/plans/FANTASY_DCI_PLAN.md, Appendix B). Additive +
  // idempotent. All ids are UUID strings, all timestamps ISO-8601 UTC TEXT.
  // CaptionKey values are stored as the 8 keys ('GE1'…'MP'), never long names.
  // ---------------------------------------------------------------------------
  `CREATE TABLE IF NOT EXISTS fantasy_leagues (
     league_id      TEXT PRIMARY KEY,
     slug           TEXT NOT NULL UNIQUE,
     name           TEXT NOT NULL,
     owner_user_id  TEXT NOT NULL,
     season         TEXT NOT NULL,
     status         TEXT NOT NULL DEFAULT 'setup',  -- setup|quiz|scheduled|drafting|active|complete|canceled
     config_json    TEXT NOT NULL,                  -- validated LeagueConfig (Appendix E.0)
     max_members    INTEGER NOT NULL DEFAULT 12,
     payment_status TEXT NOT NULL DEFAULT 'none',   -- none|paid|refunded (reserved)
     payment_ref    TEXT,
     created_at     TEXT NOT NULL,
     updated_at     TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_leagues_owner  ON fantasy_leagues (owner_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_leagues_season ON fantasy_leagues (season, status)`,

  `CREATE TABLE IF NOT EXISTS fantasy_members (
     league_id           TEXT NOT NULL,
     user_id             TEXT NOT NULL,
     role                TEXT NOT NULL DEFAULT 'member', -- owner|member
     corps_name          TEXT,
     show_title          TEXT,
     corps_logo_media_id TEXT,
     corps_color         TEXT,
     quiz_score          REAL,
     draft_position      INTEGER,
     status              TEXT NOT NULL DEFAULT 'active', -- active|removed
     joined_at           TEXT NOT NULL,
     PRIMARY KEY (league_id, user_id)
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_members_user ON fantasy_members (user_id)`,

  `CREATE TABLE IF NOT EXISTS fantasy_invites (
     invite_id   TEXT PRIMARY KEY,
     league_id   TEXT NOT NULL,
     token       TEXT NOT NULL UNIQUE,
     created_by  TEXT NOT NULL,
     email       TEXT,
     max_uses    INTEGER NOT NULL DEFAULT 1,
     used_count  INTEGER NOT NULL DEFAULT 0,
     expires_at  TEXT NOT NULL,
     revoked_at  TEXT,
     created_at  TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_invites_league ON fantasy_invites (league_id)`,

  `CREATE TABLE IF NOT EXISTS fantasy_quiz_questions (
     question_id    TEXT PRIMARY KEY,
     prompt         TEXT NOT NULL,
     choices_json   TEXT NOT NULL,           -- JSON array of 2..6 strings
     correct_index  INTEGER NOT NULL,
     explanation    TEXT,
     difficulty     TEXT NOT NULL,           -- easy|medium|hard
     tags_json      TEXT NOT NULL DEFAULT '[]',
     active         INTEGER NOT NULL DEFAULT 1,
     author_user_id TEXT NOT NULL,
     created_at     TEXT NOT NULL,
     updated_at     TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_questions_active ON fantasy_quiz_questions (active, difficulty)`,

  `CREATE TABLE IF NOT EXISTS fantasy_quiz_attempts (
     attempt_id        TEXT PRIMARY KEY,
     league_id         TEXT NOT NULL,
     user_id           TEXT NOT NULL,
     question_ids_json TEXT NOT NULL,        -- ordered JSON array of question_id served
     answers_json      TEXT NOT NULL DEFAULT '[]', -- ordered JSON array of chosen indexes
     raw_score         REAL,
     max_score         REAL,
     weighted_score    REAL,                 -- raw/max, 0..1
     started_at        TEXT NOT NULL,
     completed_at      TEXT
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_fantasy_attempt_completed
     ON fantasy_quiz_attempts (league_id, user_id) WHERE completed_at IS NOT NULL`,

  `CREATE TABLE IF NOT EXISTS fantasy_drafts (
     draft_id        TEXT PRIMARY KEY,
     league_id       TEXT NOT NULL UNIQUE,
     status          TEXT NOT NULL DEFAULT 'scheduled', -- scheduled|live|paused|complete
     scheduled_at    TEXT,
     order_json      TEXT,                  -- JSON array of user_id (base round-1 order)
     draft_type      TEXT NOT NULL,         -- snake|linear (frozen from config)
     pick_seconds    INTEGER NOT NULL DEFAULT 60,
     total_rounds    INTEGER NOT NULL,      -- = sum(captionCaps)
     current_pick_no INTEGER NOT NULL DEFAULT 0, -- 0-based global counter
     current_user_id TEXT,
     pick_deadline_at TEXT,
     started_at      TEXT,
     completed_at    TEXT
   )`,

  `CREATE TABLE IF NOT EXISTS fantasy_picks (
     pick_id            TEXT PRIMARY KEY,
     league_id          TEXT NOT NULL,
     user_id            TEXT NOT NULL,
     corps_key          TEXT NOT NULL,
     caption            TEXT NOT NULL,       -- one of the 8 keys
     round              INTEGER NOT NULL,
     pick_no            INTEGER NOT NULL,
     caption_slot_index INTEGER NOT NULL,    -- 1-based within (user, caption)
     weight             REAL NOT NULL DEFAULT 1.0,
     auto_picked        INTEGER NOT NULL DEFAULT 0,
     created_at         TEXT NOT NULL
   )`,
  // U1: a (corps,caption) is owned by at most one member in a league.
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_fantasy_pick_corps_caption
     ON fantasy_picks (league_id, corps_key, caption)`,
  // U2: one caption per corps per member (relied on under default oneCaptionPerCorps=true).
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_fantasy_pick_user_corps
     ON fantasy_picks (league_id, user_id, corps_key)`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_picks_user ON fantasy_picks (league_id, user_id)`,

  `CREATE TABLE IF NOT EXISTS fantasy_standings (
     league_id                TEXT NOT NULL,
     user_id                  TEXT NOT NULL,
     through_competition_slug TEXT,
     total_score              REAL NOT NULL DEFAULT 0,
     ge_score                 REAL NOT NULL DEFAULT 0,
     visual_score             REAL NOT NULL DEFAULT 0,
     music_score              REAL NOT NULL DEFAULT 0,
     breakdown_json           TEXT NOT NULL DEFAULT '{}',
     rank                     INTEGER,
     computed_at              TEXT NOT NULL,
     is_final                 INTEGER NOT NULL DEFAULT 0,
     PRIMARY KEY (league_id, user_id)
   )`,

  `CREATE TABLE IF NOT EXISTS fantasy_notifications (
     notif_id      TEXT PRIMARY KEY,
     user_id       TEXT NOT NULL,
     league_id     TEXT,
     kind          TEXT NOT NULL,
     payload_json  TEXT NOT NULL DEFAULT '{}',
     read_at       TEXT,
     email_sent_at TEXT,
     push_sent_at  TEXT,
     created_at    TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_notifs_user ON fantasy_notifications (user_id, read_at)`,

  // Reserved; empty until M5 (push).
  `CREATE TABLE IF NOT EXISTS fantasy_push_subscriptions (
     user_id    TEXT NOT NULL,
     endpoint   TEXT NOT NULL,
     p256dh     TEXT NOT NULL,
     auth       TEXT NOT NULL,
     created_at TEXT NOT NULL,
     PRIMARY KEY (user_id, endpoint)
   )`,

  // Scheduled jobs — drives draft reminders + season-complete via cron (Appendix H.4).
  `CREATE TABLE IF NOT EXISTS fantasy_scheduled_jobs (
     job_id       TEXT PRIMARY KEY,
     league_id    TEXT,
     kind         TEXT NOT NULL,         -- draft_soon_60|draft_soon_10|draft_start|...
     due_at       TEXT NOT NULL,
     payload_json TEXT NOT NULL DEFAULT '{}',
     done_at      TEXT,
     created_at   TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_jobs_due ON fantasy_scheduled_jobs (done_at, due_at)`,

  `CREATE TABLE IF NOT EXISTS fantasy_admin_audit (
     audit_id      TEXT PRIMARY KEY,
     actor_user_id TEXT NOT NULL,
     action        TEXT NOT NULL,
     league_id     TEXT,
     before_json   TEXT,
     after_json    TEXT,
     created_at    TEXT NOT NULL
   )`,
  // Fantasy corps logos (plan §19.2 R1): a DEDICATED media table so logo uploads
  // never touch show_pages/show_media. Served via /api/fantasy-media/$id.
  `CREATE TABLE IF NOT EXISTS fantasy_media (
     media_id    TEXT PRIMARY KEY,
     league_id   TEXT NOT NULL,
     user_id     TEXT NOT NULL,
     r2_key      TEXT NOT NULL,
     width       INTEGER,
     height      INTEGER,
     uploaded_by TEXT NOT NULL,
     uploaded_at TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_fantasy_media_league ON fantasy_media (league_id, user_id)`,
];

/**
 * Lazily create the shared client, apply PRAGMAs, and ensure the schema — exactly
 * once per process. Subsequent calls return the same ready client. On failure the
 * init promise is cleared so the next caller retries instead of caching a broken
 * client.
 */
export const getContributionsDb = (): Promise<Client> => {
  if (!initialized) {
    initialized = (async () => {
      const db = (sharedDb ??= createClient({ url: dbUrl }));
      for (const pragma of PRAGMAS) await db.execute(pragma);
      await db.batch(SCHEMA, 'write');
      return db;
    })().catch((cause) => {
      initialized = null;
      sharedDb = null;
      throw cause;
    });
  }
  return initialized;
};

/** Test/maintenance escape hatch: drop the cached client so the next call reconnects. */
export const __resetContributionsDb = () => {
  sharedDb?.close?.();
  sharedDb = null;
  initialized = null;
};
