// Client-safe helper: rewrite DCI asset URLs through our caching proxy
// (`/api/media`) so images are served from our own cache and survive the source
// being taken down. Non-DCI (or unparseable) URLs are returned untouched.

import { CATALOG_IMAGE_HOSTS } from './merch-image-hosts.generated';

const PROXY_HOSTS = new Set(['production.assets.dci.org', 'images.dci.org']);

// Public merchant image CDNs (suffix-matched) we'll fetch-on-miss + resize for the
// merch catalog. These are well-known shared CDNs, not arbitrary origins, so this
// stays SSRF-safe; self-hosted store images (e.g. WooCommerce on the store's own
// domain) are NOT matched and pass through un-proxied.
const IMAGE_CDN_SUFFIXES = [
  'shopify.com',
  'shopifycdn.com',
  'squarespace-cdn.com',
  'squarespace.com',
  'wixstatic.com',
  'bigcommerce.com',
  'bigcartel.com',
  'printify.com',
  // Shared print-on-demand / merch platforms many corps storefronts embed. These
  // commonly block hot-linking by browser referrer, so the catalog images break
  // when loaded directly — routing them through our server-side proxy (which has
  // no referrer and caches the bytes) both fixes loading and makes them durable.
  'bonfireassets.com',
  'fourthwall.dev',
  'fourthwall.com',
  'alchemyprinting.com',
  'editmysite.com', // Weebly/Square Online store CDN (numbered subdomains → suffix)
  'inksoft.com', // InkSoft POD store CDN
  // Self-hosted corps storefronts + one-off hosts (the S3 item bucket, etc.) are
  // covered automatically by CATALOG_IMAGE_HOSTS below — no manual edits needed.
  // Self-hosted corps storefronts (the corps' own public domain). Add new ones
  // here as stores are onboarded — see scripts/warmMerchImages.ts to spot the
  // hosts in the catalog that aren't yet proxied.
  'hawthornecaballeros.org',
  'mbiarts.org',
  'dreamtoperform.org',
] as const;

// Exact image hosts present in the ingested merch catalog — auto-generated by
// sdk/scripts/genMerchImageHosts.ts so new stores' hosts self-register on a data
// refresh (no manual allowlist edits). Exact match keeps it SSRF-safe.
const CATALOG_HOSTS = new Set(CATALOG_IMAGE_HOSTS);

/** True when `host` is an asset host we may fetch-on-miss + cache + resize. */
export function isProxiableImageHost(host: string): boolean {
  if (PROXY_HOSTS.has(host) || CATALOG_HOSTS.has(host)) return true;
  return IMAGE_CDN_SUFFIXES.some((s) => host === s || host.endsWith(`.${s}`));
}

/**
 * Route an asset URL through our caching proxy (`/api/media`).
 *
 * By default only DCI-hosted assets are proxied (the endpoint can fetch-on-miss
 * for those); other hosts are returned untouched. Pass `assumeCached: true` for
 * assets we've already stored in `media_cache` via the SDK's `MediaService`
 * (e.g. corps-site favicons) — the endpoint serves cache hits regardless of host,
 * so proxying them uses our durable copy instead of the original.
 */
export function proxiedImage(
  url: string | null | undefined,
  options?: { assumeCached?: boolean; width?: number; dark?: boolean }
): string | null {
  if (!url) return null;
  const w = options?.width ? `&w=${Math.round(options.width)}` : '';
  // `merch-product:` keys are stable local cache references written during ingest.
  // They're not real URLs, so route them through the proxy directly.
  if (url.startsWith('merch-product:')) return `/api/media?u=${encodeURIComponent(url)}${w}`;
  // `&dark=1` asks for a luminance-inverted (light-ink) variant for dark mode;
  // only meaningful with a width (the proxy needs one to size the variant).
  const d = options?.dark && options?.width ? '&dark=1' : '';
  if (options?.assumeCached) return `/api/media?u=${encodeURIComponent(url)}${w}${d}`;
  try {
    const host = new URL(url).host;
    if (!isProxiableImageHost(host)) return url;
    return `/api/media?u=${encodeURIComponent(url)}${w}${d}`;
  } catch {
    return url;
  }
}
