// AUTO-GENERATED by sdk/scripts/genMerchImageHosts.ts — do not edit by hand.
// Exact image hosts present in the ingested merch catalog (17 hosts).
// media.ts unions these into the /api/media fetch-on-miss allowlist (SSRF-safe:
// only hosts we ingested). Re-run the generator after a merch data refresh.
export const CATALOG_IMAGE_HOSTS: readonly string[] = [
  '131232652.cdn6.editmysite.com',
  '132223912.cdn6.editmysite.com',
  '138271369.cdn6.editmysite.com',
  'alchemyprinting.com',
  'cdn.inksoft.com',
  'cdn.shopify.com',
  'cdn11.bigcommerce.com',
  'dreamtoperform.org',
  'dynamic.bonfireassets.com',
  'funlinerproductions.com',
  'hawthornecaballeros.org',
  'images.squarespace-cdn.com',
  'imgproxy.fourthwall.dev',
  'mbiarts.org',
  'static.wixstatic.com',
  'static1.squarespace.com',
  'www.lotriot.com',
];
