// Single favorite corps — persisted to localStorage, drives the site accent color,
// logo palette, and favicon. Only one corps can be favorited at a time.
import { useSyncExternalStore } from 'react';
import { createStore } from '@xstate/store';
import { corpsPalette, hexToOklch, oklchToRgb, rgbToHex, FALLBACK_PRIMARY } from '@sdk/src/corpsColors.js';
import type { CorpsBrandColors } from '@sdk/src/corpsColors.js';
import { themeStore } from './theme-store';

export const FAVORITE_STORAGE_KEY = 'corps-place-favorite-corps';
const VERSION = 2;

// ── Favicon: the site logo, recolored to the corps's brand ────────────────────
// The favicon IS the site logo (public/logo.svg), recolored exactly like the
// on-page <Logo> does — the logo's 6 palette fills are the *defaults* of the
// --logo-* CSS variables, and CSS re-derives those from --primary via relative
// oklch (app.css §logo palette). We replicate those same formulas in JS and bake
// the resulting hex values into the SVG, since a <link rel="icon"> data: URL has
// no access to the page's CSS variables. The logo markup is fetched at runtime
// (cached) rather than bundled, so its ~63 KB stays out of the JS.

// The default fills baked into public/logo.svg, paired with the relative-oklch
// derivation each one gets from --primary. Keep in sync with app.css §logo.
type Lch = { l: number; c: number; h: number };
const LOGO_FILLS: { hex: string; derive: (p: Lch) => Lch }[] = [
  { hex: '#feb403', derive: (p) => ({ l: 0.72, c: p.c, h: p.h + 12 }) }, // --logo-accent
  { hex: '#fd5007', derive: (p) => ({ l: p.l + 0.02, c: p.c * 1.15, h: p.h }) }, // --logo-accent-vivid
  { hex: '#fe7f02', derive: (p) => ({ l: p.l + 0.08, c: p.c * 0.75, h: p.h }) }, // --logo-accent-muted
  { hex: '#0c2e1d', derive: (p) => ({ l: 0.17, c: p.c * 0.3, h: p.h + 50 }) }, // --logo-dark
  { hex: '#e22517', derive: (p) => ({ l: p.l - 0.1, c: p.c * 1.1, h: p.h }) }, // --logo-detail
  { hex: '#fbfbf2', derive: (p) => ({ l: 0.96, c: p.c * 0.08, h: p.h }) }, // --logo-light
];

const clamp01 = (n: number) => Math.max(0, Math.min(1, n));
const lchToHex = ({ l, c, h }: Lch): string => {
  const [r, g, b] = oklchToRgb({ l: clamp01(l), c: Math.max(0, c), h: ((h % 360) + 360) % 360 });
  return rgbToHex(r, g, b);
};

/** Parse an `oklch(l c h)` string (the form --logo-dark is stored in). */
const parseOklchString = (s: string): Lch | null => {
  const m = /oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.-]+)/i.exec(s);
  return m ? { l: +m[1], c: +m[2], h: +m[3] } : null;
};

// Fetch + cache the logo markup once (it's a static asset, so this is ~free after
// the browser cache warms). Module-level so repeated favorites reuse it.
let logoMarkupPromise: Promise<string | null> | null = null;
const loadLogoMarkup = (): Promise<string | null> => {
  if (!logoMarkupPromise) {
    logoMarkupPromise = fetch('/logo.svg')
      .then((r) => (r.ok ? r.text() : null))
      .catch(() => null);
  }
  return logoMarkupPromise;
};

/** Recolor the site logo to a corps's palette and return it as a data: URL, or
 *  null if the logo can't be loaded (caller falls back to the default favicon).
 *  `logoDark` (oklch string) overrides the derived structural-dark fill so the
 *  favicon matches what the page renders. */
async function generateLogoFavicon(
  primaryHex: string,
  logoDark: string | null
): Promise<string | null> {
  const primary = hexToOklch(primaryHex);
  const markup = await loadLogoMarkup();
  if (!primary || !markup) return null;
  const darkOverride = logoDark ? parseOklchString(logoDark) : null;
  let out = markup;
  for (const { hex, derive } of LOGO_FILLS) {
    const color =
      hex === '#0c2e1d' && darkOverride ? lchToHex(darkOverride) : lchToHex(derive(primary));
    out = out.replaceAll(hex, color);
  }
  return `data:image/svg+xml,${encodeURIComponent(out)}`;
}

// ── Input / persisted types ───────────────────────────────────────────────────

export interface FavoriteCorpsInput {
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
}

/** Extracts the minimum fields needed for a favorite from a corps directory row. */
export function toFavoriteInput(corps: {
  corps_key: string;
  name: string;
  slug: string | null;
  color_primary: string | null;
  color_secondary: string | null;
}): FavoriteCorpsInput {
  return {
    corpsKey: corps.corps_key,
    name: corps.name,
    slug: corps.slug,
    colorPrimary: corps.color_primary,
    colorSecondary: corps.color_secondary,
  };
}

// Versioned, validated persisted shape. All CSS values are generated by our own
// palette functions — never user-supplied strings (plan §Data Shape, invariant 6).
export interface PersistedFavorite {
  version: number;
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  /** Pre-computed --logo-dark for the no-flash script. null → CSS derives from --primary. */
  logoDark: string | null;
  /** Pre-generated favicon SVG as a data: URL. Used by no-flash script + setFavicon(). */
  faviconSvg: string;
  addedAt: string;
}

// ── Branding computation ──────────────────────────────────────────────────────
// Single entry point for deriving all CSS variables + favicon from a corps input.
// Decoupled from the store so it can be tested independently (plan §Tests).

export interface FavoriteBranding {
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  logoDark: string | null;
  faviconSvg: string;
}

export function computeFavoriteBranding(input: FavoriteCorpsInput): FavoriteBranding {
  const colors: Partial<CorpsBrandColors> = input.colorPrimary
    ? { primary: input.colorPrimary, secondary: input.colorSecondary }
    : {};
  const light = corpsPalette(colors, 'light');
  const dark = corpsPalette(colors, 'dark');
  const logoDark = computeLogoDark(input.colorSecondary ?? null, light.accent);
  return {
    lightPrimary: light.accent,
    lightPrimaryForeground: light.accentFg,
    darkPrimary: dark.accent,
    darkPrimaryForeground: dark.accentFg,
    logoDark,
    // The recolored-logo favicon is generated asynchronously (it fetches the logo
    // markup) by applyFavoriteBranding, then persisted back for the next load's
    // no-flash before-paint set. Empty here → no-flash leaves the default favicon.
    faviconSvg: '',
  };
}

// ── Secondary color → --logo-dark with guardrails ─────────────────────────────
// (plan §Logo Palette: clamp weak/low-chroma secondaries so the structural dark
// fill stays legible. If secondary is missing or too close to primary, derive
// from primary instead.)

const DARK_L = 0.17;
const DARK_C_MIN = 0.02;
const DARK_C_MAX = 0.06;

function computeLogoDark(secondaryHex: string | null, primaryOklch: string): string | null {
  if (!secondaryHex) return null;
  const sec = hexToOklch(secondaryHex);
  if (!sec) return null;
  // Clamp chroma so the fill stays structurally dark, not a saturated accent.
  const c = Math.max(DARK_C_MIN, Math.min(sec.c * 0.3, DARK_C_MAX));
  // If chroma was already near-zero (grayscale secondary), skip — let CSS derive.
  if (sec.c < 0.01) return null;
  return `oklch(${DARK_L} ${+c.toFixed(3)} ${+sec.h.toFixed(1)})`;
}

// ── Favicon helpers ───────────────────────────────────────────────────────────

export function setFavicon(href: string): void {
  if (typeof document === 'undefined') return;
  // Update both the tab favicon and the apple-touch / homescreen icon so an
  // installed PWA / bookmarked shortcut picks up the favorited corps's mark too.
  for (const [rel, type] of [
    ['icon', 'image/svg+xml'],
    ['apple-touch-icon', null],
  ] as const) {
    const sel = `link[rel="${rel}"][data-app-icon]`;
    let link = document.querySelector<HTMLLinkElement>(sel);
    if (!link) {
      link = document.createElement('link');
      link.rel = rel;
      if (type) link.type = type;
      link.setAttribute('data-app-icon', 'true');
      document.head.appendChild(link);
    }
    link.href = href;
  }
}

/** Updates the browser/PWA chrome color (address bar, task switcher, splash) to
 *  match the favorited corps. Uses the raw corps hex so every UA can parse it. */
export function setThemeColor(color: string | null): void {
  if (typeof document === 'undefined') return;
  let meta = document.querySelector<HTMLMetaElement>('meta[name="theme-color"][data-app-theme]');
  if (!meta) {
    meta = document.createElement('meta');
    meta.name = 'theme-color';
    meta.setAttribute('data-app-theme', 'true');
    document.head.appendChild(meta);
  }
  meta.content = color ?? '#0b0b0c';
}

// ── Persist / clean ───────────────────────────────────────────────────────────

function toPersisted(input: FavoriteCorpsInput, previousAddedAt?: string): PersistedFavorite {
  const branding = computeFavoriteBranding(input);
  return {
    version: VERSION,
    corpsKey: input.corpsKey,
    name: input.name,
    slug: input.slug,
    colorPrimary: input.colorPrimary,
    colorSecondary: input.colorSecondary,
    ...branding,
    addedAt: previousAddedAt ?? new Date().toISOString(),
  };
}

/** Validates + cleans a stored favorite. Rejects corrupt data; recomputes
 *  palettes from stored hex so format drift self-heals. Preserves `addedAt`
 *  from a valid v2 payload (plan §Data Shape). */
export function cleanFavorite(raw: unknown): PersistedFavorite | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  // Version gate — unknown or mismatched versions get recomputed fresh.
  const ver = r.version;
  if (typeof r.corpsKey !== 'string' || typeof r.name !== 'string') return null;

  const previousAddedAt = ver === VERSION && typeof r.addedAt === 'string' ? r.addedAt : undefined;

  return toPersisted(
    {
      corpsKey: r.corpsKey,
      name: r.name,
      slug: typeof r.slug === 'string' ? r.slug : null,
      colorPrimary: typeof r.colorPrimary === 'string' ? r.colorPrimary : null,
      colorSecondary: typeof r.colorSecondary === 'string' ? r.colorSecondary : null,
    },
    previousAddedAt
  );
}

function persist(fav: PersistedFavorite | null): void {
  try {
    if (fav) {
      localStorage.setItem(FAVORITE_STORAGE_KEY, JSON.stringify(fav));
    } else {
      localStorage.removeItem(FAVORITE_STORAGE_KEY);
    }
  } catch {
    /* private mode / quota — favorite stays in-memory */
  }
}

// ── DOM application ───────────────────────────────────────────────────────────
// Single shared path for React store + no-flash script (plan §Switching Favorites).

export function applyFavoriteBranding(fav: PersistedFavorite): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  const dark = root.classList.contains('dark');
  root.style.setProperty('--primary', dark ? fav.darkPrimary : fav.lightPrimary);
  root.style.setProperty(
    '--primary-foreground',
    dark ? fav.darkPrimaryForeground : fav.lightPrimaryForeground
  );
  if (fav.logoDark) {
    root.style.setProperty('--logo-dark', fav.logoDark);
  } else {
    root.style.removeProperty('--logo-dark');
  }
  root.setAttribute('data-fav-active', '');
  setThemeColor(fav.colorPrimary ?? (dark ? fav.darkPrimary : fav.lightPrimary));

  // Favicon = the site logo recolored to this corps. Use the already-generated
  // data URL immediately when present (set before-paint by the no-flash script,
  // or cached this session); otherwise generate it (fetches the logo markup) and
  // set + persist it so the next load can paint it instantly. Falls back to the
  // default logo when the corps has no brand color or the logo can't be loaded.
  const primaryHex = fav.colorPrimary;
  const cached = fav.faviconSvg || (primaryHex ? faviconCache.get(faviconKey(fav)) : null);
  if (cached) {
    setFavicon(cached);
  } else if (primaryHex) {
    void generateLogoFavicon(primaryHex, fav.logoDark).then((url) => {
      if (!url || favoriteCorpsStore.getSnapshot().context.favorite?.corpsKey !== fav.corpsKey)
        return;
      faviconCache.set(faviconKey(fav), url);
      setFavicon(url);
      persist({ ...fav, faviconSvg: url });
    });
  } else {
    setFavicon('/logo.svg');
  }
}

// Recolored-logo favicons generated this session, keyed by corps + structural
// dark, so re-applying the same favorite (e.g. on theme toggle) is instant and
// doesn't re-run the SVG recolor or re-persist.
const faviconCache = new Map<string, string>();
const faviconKey = (fav: PersistedFavorite) => `${fav.colorPrimary}|${fav.logoDark ?? ''}`;

export function clearFavoriteBranding(): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  root.style.removeProperty('--primary');
  root.style.removeProperty('--primary-foreground');
  root.style.removeProperty('--logo-dark');
  root.removeAttribute('data-fav-active');
  setFavicon('/logo.svg');
  setThemeColor(null);
}

// Backward-compat alias kept for existing call sites (theme store, etc.).
export const applyFavoriteColors = applyFavoriteBranding;

// ── Store ────────────────────────────────────────────────────────────────────

export const favoriteCorpsStore = createStore({
  context: { favorite: null as PersistedFavorite | null },
  on: {
    set: (_context, event: { input: FavoriteCorpsInput }) => ({
      favorite: toPersisted(event.input),
    }),
    clear: () => ({ favorite: null }),
    hydrate: (_context, event: { favorite: PersistedFavorite | null }) => ({
      favorite: event.favorite,
    }),
  },
});

favoriteCorpsStore.subscribe((snapshot) => {
  const fav = snapshot.context.favorite;
  persist(fav);
  if (fav) applyFavoriteBranding(fav);
  else clearFavoriteBranding();
});

themeStore.subscribe(() => {
  const fav = favoriteCorpsStore.getSnapshot().context.favorite;
  if (fav) applyFavoriteBranding(fav);
});

// ── Hydration ─────────────────────────────────────────────────────────────────

function hydrateFavorite(): void {
  if (typeof localStorage === 'undefined') return;
  try {
    const raw = localStorage.getItem(FAVORITE_STORAGE_KEY);
    const saved = raw ? cleanFavorite(JSON.parse(raw)) : null;
    if (!saved && raw) {
      // Corrupt favorite — clean up so no-flash script doesn't re-read stale data.
      try {
        localStorage.removeItem(FAVORITE_STORAGE_KEY);
      } catch {}
    }
    favoriteCorpsStore.trigger.hydrate({ favorite: saved });
  } catch {
    /* ignore corrupt storage */
  }
}

if (typeof window !== 'undefined') hydrateFavorite();

// ── React hooks ──────────────────────────────────────────────────────────────

const SERVER_FAVORITE: PersistedFavorite | null = null;

const subscribeFavorite = (onChange: () => void) => {
  const sub = favoriteCorpsStore.subscribe(onChange);
  return () => sub.unsubscribe();
};

export function useFavoriteCorps(): PersistedFavorite | null {
  return useSyncExternalStore(
    subscribeFavorite,
    () => favoriteCorpsStore.getSnapshot().context.favorite,
    () => SERVER_FAVORITE
  );
}

export function useIsFavorite(corpsKey: string): boolean {
  // Subscribe with a boolean snapshot rather than the whole favorite object, so
  // toggling one favorite only re-renders the cards whose state actually flips —
  // not every FavoriteCorpsButton on the grid.
  return useSyncExternalStore(
    subscribeFavorite,
    () => favoriteCorpsStore.getSnapshot().context.favorite?.corpsKey === corpsKey,
    () => false
  );
}
