// Single favorite corps — persisted to localStorage, drives the site accent color,
// logo palette, and favicon. Only one corps can be favorited at a time.
import { useSyncExternalStore } from 'react';
import { createStore } from '@xstate/store';
import { corpsPalette, hexToOklch, FALLBACK_PRIMARY } from '@sdk/src/corpsColors.js';
import type { CorpsBrandColors } from '@sdk/src/corpsColors.js';
import { themeStore } from './theme-store';

export const FAVORITE_STORAGE_KEY = 'corps-place-favorite-corps';
const VERSION = 2;

// ── Pure SVG favicon generator ────────────────────────────────────────────────
// A simple mark generated from the corps palette so the no-flash script can set
// it before React mounts. Renders as a stacked shape: an outer circle in the
// primary accent, an inner cutout in the logo-dark (or soft tone when absent),
// and a tiny highlight dot. No CSS variables — actual oklch() values are baked
// in so it works inside an <img> / <link rel="icon"> context.

const FAVICON_SVG = (accent: string, accentFg: string, logoDark: string | null): string => {
  // When no logoDark is available use a very low-L, low-C tone from the
  // accent foreground so the inner shape stays soft rather than harsh black.
  const inner = logoDark ?? colorMixOklch(accentFg, accent, 0.85);
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
    `<circle cx="32" cy="32" r="30" fill="${accent}"/>`,
    `<circle cx="32" cy="32" r="14" fill="${inner}"/>`,
    `<circle cx="22" cy="24" r="4" fill="${accentFg}" opacity=".55"/>`,
    '</svg>',
  ].join('');
};

/** Quick-and-dirty oklch color-mix for the favicon generator (no external deps). */
function colorMixOklch(a: string, b: string, ratio: number): string {
  const parse = (s: string) => {
    const m = /oklch\(([^)]+)\)/.exec(s);
    if (!m) return null;
    const parts = m[1].split(/\s+/).map(Number);
    return { l: parts[0], c: parts[1], h: parts[2] };
  };
  const pa = parse(a);
  const pb = parse(b);
  if (!pa || !pb) return a;
  return `oklch(${(pa.l * (1 - ratio) + pb.l * ratio).toFixed(3)} ${(pa.c * (1 - ratio) + pb.c * ratio).toFixed(3)} ${(pa.h * (1 - ratio) + pb.h * ratio).toFixed(1)})`;
}

// ── Input / persisted types ───────────────────────────────────────────────────

export interface FavoriteCorpsInput {
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
}

/** Extracts the minimum fields needed for a favorite from a corps directory row. */
export function toFavoriteInput(corps: {
  corps_key: string;
  name: string;
  slug: string | null;
  color_primary: string | null;
  color_secondary: string | null;
}): FavoriteCorpsInput {
  return {
    corpsKey: corps.corps_key,
    name: corps.name,
    slug: corps.slug,
    colorPrimary: corps.color_primary,
    colorSecondary: corps.color_secondary,
  };
}

// Versioned, validated persisted shape. All CSS values are generated by our own
// palette functions — never user-supplied strings (plan §Data Shape, invariant 6).
export interface PersistedFavorite {
  version: number;
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  /** Pre-computed --logo-dark for the no-flash script. null → CSS derives from --primary. */
  logoDark: string | null;
  /** Pre-generated favicon SVG as a data: URL. Used by no-flash script + setFavicon(). */
  faviconSvg: string;
  addedAt: string;
}

// ── Branding computation ──────────────────────────────────────────────────────
// Single entry point for deriving all CSS variables + favicon from a corps input.
// Decoupled from the store so it can be tested independently (plan §Tests).

export interface FavoriteBranding {
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  logoDark: string | null;
  faviconSvg: string;
}

export function computeFavoriteBranding(input: FavoriteCorpsInput): FavoriteBranding {
  const colors: Partial<CorpsBrandColors> = input.colorPrimary
    ? { primary: input.colorPrimary, secondary: input.colorSecondary }
    : {};
  const light = corpsPalette(colors, 'light');
  const dark = corpsPalette(colors, 'dark');
  const logoDark = computeLogoDark(input.colorSecondary ?? null, light.accent);
  const faviconSvg = faviconDataUrl(light.accent, light.accentFg, logoDark);
  return {
    lightPrimary: light.accent,
    lightPrimaryForeground: light.accentFg,
    darkPrimary: dark.accent,
    darkPrimaryForeground: dark.accentFg,
    logoDark,
    faviconSvg,
  };
}

// ── Secondary color → --logo-dark with guardrails ─────────────────────────────
// (plan §Logo Palette: clamp weak/low-chroma secondaries so the structural dark
// fill stays legible. If secondary is missing or too close to primary, derive
// from primary instead.)

const DARK_L = 0.17;
const DARK_C_MIN = 0.02;
const DARK_C_MAX = 0.06;

function computeLogoDark(secondaryHex: string | null, primaryOklch: string): string | null {
  if (!secondaryHex) return null;
  const sec = hexToOklch(secondaryHex);
  if (!sec) return null;
  // Clamp chroma so the fill stays structurally dark, not a saturated accent.
  const c = Math.max(DARK_C_MIN, Math.min(sec.c * 0.3, DARK_C_MAX));
  // If chroma was already near-zero (grayscale secondary), skip — let CSS derive.
  if (sec.c < 0.01) return null;
  return `oklch(${DARK_L} ${+c.toFixed(3)} ${+sec.h.toFixed(1)})`;
}

// ── Favicon helpers ───────────────────────────────────────────────────────────

function faviconDataUrl(accent: string, accentFg: string, logoDark: string | null): string {
  const svg = FAVICON_SVG(accent, accentFg, logoDark);
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export function setFavicon(href: string): void {
  if (typeof document === 'undefined') return;
  const sel = 'link[rel="icon"][data-app-icon]';
  let link = document.querySelector<HTMLLinkElement>(sel);
  if (!link) {
    link = document.createElement('link');
    link.rel = 'icon';
    link.type = 'image/svg+xml';
    link.setAttribute('data-app-icon', 'true');
    document.head.appendChild(link);
  }
  link.href = href;
}

// ── Persist / clean ───────────────────────────────────────────────────────────

function toPersisted(input: FavoriteCorpsInput, previousAddedAt?: string): PersistedFavorite {
  const branding = computeFavoriteBranding(input);
  return {
    version: VERSION,
    corpsKey: input.corpsKey,
    name: input.name,
    slug: input.slug,
    colorPrimary: input.colorPrimary,
    colorSecondary: input.colorSecondary,
    ...branding,
    addedAt: previousAddedAt ?? new Date().toISOString(),
  };
}

/** Validates + cleans a stored favorite. Rejects corrupt data; recomputes
 *  palettes from stored hex so format drift self-heals. Preserves `addedAt`
 *  from a valid v2 payload (plan §Data Shape). */
export function cleanFavorite(raw: unknown): PersistedFavorite | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  // Version gate — unknown or mismatched versions get recomputed fresh.
  const ver = r.version;
  if (typeof r.corpsKey !== 'string' || typeof r.name !== 'string') return null;

  const previousAddedAt = ver === VERSION && typeof r.addedAt === 'string' ? r.addedAt : undefined;

  return toPersisted(
    {
      corpsKey: r.corpsKey,
      name: r.name,
      slug: typeof r.slug === 'string' ? r.slug : null,
      colorPrimary: typeof r.colorPrimary === 'string' ? r.colorPrimary : null,
      colorSecondary: typeof r.colorSecondary === 'string' ? r.colorSecondary : null,
    },
    previousAddedAt
  );
}

function persist(fav: PersistedFavorite | null): void {
  try {
    if (fav) {
      localStorage.setItem(FAVORITE_STORAGE_KEY, JSON.stringify(fav));
    } else {
      localStorage.removeItem(FAVORITE_STORAGE_KEY);
    }
  } catch {
    /* private mode / quota — favorite stays in-memory */
  }
}

// ── DOM application ───────────────────────────────────────────────────────────
// Single shared path for React store + no-flash script (plan §Switching Favorites).

export function applyFavoriteBranding(fav: PersistedFavorite): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  const dark = root.classList.contains('dark');
  root.style.setProperty('--primary', dark ? fav.darkPrimary : fav.lightPrimary);
  root.style.setProperty(
    '--primary-foreground',
    dark ? fav.darkPrimaryForeground : fav.lightPrimaryForeground
  );
  if (fav.logoDark) {
    root.style.setProperty('--logo-dark', fav.logoDark);
  } else {
    root.style.removeProperty('--logo-dark');
  }
  root.setAttribute('data-fav-active', '');
  setFavicon(fav.faviconSvg);
}

export function clearFavoriteBranding(): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  root.style.removeProperty('--primary');
  root.style.removeProperty('--primary-foreground');
  root.style.removeProperty('--logo-dark');
  root.removeAttribute('data-fav-active');
  setFavicon('/logo.svg');
}

// Backward-compat alias kept for existing call sites (theme store, etc.).
export const applyFavoriteColors = applyFavoriteBranding;

// ── Store ────────────────────────────────────────────────────────────────────

export const favoriteCorpsStore = createStore({
  context: { favorite: null as PersistedFavorite | null },
  on: {
    set: (_context, event: { input: FavoriteCorpsInput }) => ({
      favorite: toPersisted(event.input),
    }),
    clear: () => ({ favorite: null }),
    hydrate: (_context, event: { favorite: PersistedFavorite | null }) => ({
      favorite: event.favorite,
    }),
  },
});

favoriteCorpsStore.subscribe((snapshot) => {
  const fav = snapshot.context.favorite;
  persist(fav);
  if (fav) applyFavoriteBranding(fav);
  else clearFavoriteBranding();
});

themeStore.subscribe(() => {
  const fav = favoriteCorpsStore.getSnapshot().context.favorite;
  if (fav) applyFavoriteBranding(fav);
});

// ── Hydration ─────────────────────────────────────────────────────────────────

function hydrateFavorite(): void {
  if (typeof localStorage === 'undefined') return;
  try {
    const raw = localStorage.getItem(FAVORITE_STORAGE_KEY);
    const saved = raw ? cleanFavorite(JSON.parse(raw)) : null;
    if (!saved && raw) {
      // Corrupt favorite — clean up so no-flash script doesn't re-read stale data.
      try {
        localStorage.removeItem(FAVORITE_STORAGE_KEY);
      } catch {}
    }
    favoriteCorpsStore.trigger.hydrate({ favorite: saved });
  } catch {
    /* ignore corrupt storage */
  }
}

if (typeof window !== 'undefined') hydrateFavorite();

// ── React hooks ──────────────────────────────────────────────────────────────

const SERVER_FAVORITE: PersistedFavorite | null = null;

const subscribeFavorite = (onChange: () => void) => {
  const sub = favoriteCorpsStore.subscribe(onChange);
  return () => sub.unsubscribe();
};

export function useFavoriteCorps(): PersistedFavorite | null {
  return useSyncExternalStore(
    subscribeFavorite,
    () => favoriteCorpsStore.getSnapshot().context.favorite,
    () => SERVER_FAVORITE
  );
}

export function useIsFavorite(corpsKey: string): boolean {
  const fav = useFavoriteCorps();
  return fav?.corpsKey === corpsKey;
}
