// Single favorite corps — persisted to a cookie (so SSR can read it), drives the
// site accent color, logo palette, and favicon. Only one corps can be favorited
// at a time. The favicon itself is generated by the /app-icon.svg server route
// from a deterministic URL (see @/lib/logo-recolor), so the same href renders
// identically on the server and client and never resets on hydration.
import { useSyncExternalStore } from 'react';
import { createStore } from '@xstate/store';
import { corpsPalette, hexToOklch, normalizeHex } from '@sdk/src/corpsColors.js';
import type { CorpsBrandColors } from '@sdk/src/corpsColors.js';
import { DEFAULT_APP_ICON_HREF, buildAppIconHref } from '@/lib/logo-recolor';
import { readFavoriteCookie, writeFavoriteCookie } from '@/lib/favorite-cookie';
import { themeStore } from './theme-store';

const VERSION = 2;
const LIGHT_THEME_COLOR = '#ffffff';
const DARK_THEME_COLOR = '#0b0b0c';

export function themeChromeColor(theme: 'light' | 'dark'): string {
  return theme === 'dark' ? DARK_THEME_COLOR : LIGHT_THEME_COLOR;
}

let brandingTransitionFrame: number | null = null;

function beginBrandingUpdate(): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  if (brandingTransitionFrame !== null) cancelAnimationFrame(brandingTransitionFrame);
  root.classList.add('branding-switching');
  brandingTransitionFrame = requestAnimationFrame(() => {
    root.classList.remove('branding-switching');
    brandingTransitionFrame = null;
  });
}

// ── Input / persisted types ───────────────────────────────────────────────────

export interface FavoriteCorpsInput {
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
}

/** Extracts the minimum fields needed for a favorite from a corps directory row. */
export function toFavoriteInput(corps: {
  corps_key: string;
  name: string;
  slug: string | null;
  color_primary: string | null;
  color_secondary: string | null;
}): FavoriteCorpsInput {
  return {
    corpsKey: corps.corps_key,
    name: corps.name,
    slug: corps.slug,
    colorPrimary: corps.color_primary,
    colorSecondary: corps.color_secondary,
  };
}

// Versioned, validated persisted shape. All CSS values are generated by our own
// palette functions — never user-supplied strings (plan §Data Shape, invariant 6).
export interface PersistedFavorite {
  version: number;
  corpsKey: string;
  name: string;
  slug: string | null;
  colorPrimary: string | null;
  colorSecondary: string | null;
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  /** Pre-computed --logo-dark for the no-flash script. null → CSS derives from --primary. */
  logoDark: string | null;
  addedAt: string;
}

// ── Branding computation ──────────────────────────────────────────────────────
// Single entry point for deriving all CSS variables from a corps input. Decoupled
// from the store so it can be tested independently (plan §Tests). The favicon is
// not computed here — it's served by /app-icon.svg from a deterministic URL built
// from colorPrimary + logoDark (see @/lib/logo-recolor).

export interface FavoriteBranding {
  lightPrimary: string;
  lightPrimaryForeground: string;
  darkPrimary: string;
  darkPrimaryForeground: string;
  logoDark: string | null;
}

export function computeFavoriteBranding(input: FavoriteCorpsInput): FavoriteBranding {
  const colors: Partial<CorpsBrandColors> = input.colorPrimary
    ? { primary: input.colorPrimary, secondary: input.colorSecondary }
    : {};
  const light = corpsPalette(colors, 'light');
  const dark = corpsPalette(colors, 'dark');
  const logoDark = computeLogoDark(input.colorSecondary ?? null);
  return {
    lightPrimary: light.accent,
    lightPrimaryForeground: light.accentFg,
    darkPrimary: dark.accent,
    darkPrimaryForeground: dark.accentFg,
    logoDark,
  };
}

// ── Secondary color → --logo-dark with guardrails ─────────────────────────────
// (plan §Logo Palette: clamp weak/low-chroma secondaries so the structural dark
// fill stays legible. If secondary is missing or too close to primary, derive
// from primary instead.)

const DARK_L = 0.17;
const DARK_C_MIN = 0.02;
const DARK_C_MAX = 0.06;

function computeLogoDark(secondaryHex: string | null): string | null {
  if (!secondaryHex) return null;
  const sec = hexToOklch(secondaryHex);
  if (!sec) return null;
  // Clamp chroma so the fill stays structurally dark, not a saturated accent.
  const c = Math.max(DARK_C_MIN, Math.min(sec.c * 0.3, DARK_C_MAX));
  // If chroma was already near-zero (grayscale secondary), skip — let CSS derive.
  if (sec.c < 0.01) return null;
  return `oklch(${DARK_L} ${+c.toFixed(3)} ${+sec.h.toFixed(1)})`;
}

// ── Favicon helpers ───────────────────────────────────────────────────────────

export function setFavicon(href: string): void {
  if (typeof document === 'undefined') return;
  // Update both the tab favicon and the apple-touch / homescreen icon so an
  // installed PWA / bookmarked shortcut picks up the favorited corps's mark too.
  // These tags are rendered by the root route's head() (so SSR is correct); here
  // we update them in place on a runtime favorite change.
  for (const [rel, type] of [
    ['icon', 'image/svg+xml'],
    ['apple-touch-icon', null],
  ] as const) {
    let link = document.querySelector<HTMLLinkElement>(`link[rel="${rel}"][data-app-icon="true"]`);
    if (!link) {
      link = document.createElement('link');
      link.rel = rel;
      link.dataset.appIcon = 'true';
      if (type) link.type = type;
      document.head.appendChild(link);
    }
    link.href = href;
  }
}

/** Updates the browser/PWA chrome color (address bar, task switcher, splash) to
 *  match the favorited corps. Uses the raw corps hex so every UA can parse it. */
export function setThemeColor(color: string | null): void {
  if (typeof document === 'undefined') return;
  let meta = document.querySelector<HTMLMetaElement>('meta[name="theme-color"]');
  if (!meta) {
    meta = document.createElement('meta');
    meta.name = 'theme-color';
    document.head.appendChild(meta);
  }
  meta.content = color ?? themeChromeColor(themeStore.getSnapshot().context.theme);
}

// ── Persist / clean ───────────────────────────────────────────────────────────

function toPersisted(input: FavoriteCorpsInput, previousAddedAt?: string): PersistedFavorite {
  const normalized = {
    ...input,
    colorPrimary: input.colorPrimary ? normalizeHex(input.colorPrimary) : null,
    colorSecondary: input.colorSecondary ? normalizeHex(input.colorSecondary) : null,
  };
  const branding = computeFavoriteBranding(normalized);
  return {
    version: VERSION,
    corpsKey: input.corpsKey,
    name: input.name,
    slug: input.slug,
    colorPrimary: normalized.colorPrimary,
    colorSecondary: normalized.colorSecondary,
    ...branding,
    addedAt: previousAddedAt ?? new Date().toISOString(),
  };
}

/** Validates + cleans a stored favorite. Rejects corrupt data; recomputes
 *  palettes from stored hex so format drift self-heals. Preserves `addedAt`
 *  from a valid v2 payload (plan §Data Shape). */
export function cleanFavorite(raw: unknown): PersistedFavorite | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  // Version gate — unknown or mismatched versions get recomputed fresh.
  const ver = r.version;
  if (typeof r.corpsKey !== 'string' || typeof r.name !== 'string') return null;

  const previousAddedAt = ver === VERSION && typeof r.addedAt === 'string' ? r.addedAt : undefined;

  return toPersisted(
    {
      corpsKey: r.corpsKey,
      name: r.name,
      slug: typeof r.slug === 'string' ? r.slug : null,
      colorPrimary: typeof r.colorPrimary === 'string' ? r.colorPrimary : null,
      colorSecondary: typeof r.colorSecondary === 'string' ? r.colorSecondary : null,
    },
    previousAddedAt
  );
}

function persist(fav: PersistedFavorite | null): void {
  // Cookie (not localStorage) so the server reads it during SSR and renders the
  // correct accent/favicon/theme-color into the initial HTML.
  writeFavoriteCookie(fav ? JSON.stringify(fav) : null);
}

// ── DOM application ───────────────────────────────────────────────────────────
// Single shared path for React store + no-flash script (plan §Switching Favorites).

export function applyFavoriteBranding(fav: PersistedFavorite): void {
  if (typeof document === 'undefined') return;
  beginBrandingUpdate();
  const root = document.documentElement;
  const dark = root.classList.contains('dark');
  root.style.setProperty('--primary', dark ? fav.darkPrimary : fav.lightPrimary);
  root.style.setProperty(
    '--primary-foreground',
    dark ? fav.darkPrimaryForeground : fav.lightPrimaryForeground
  );
  if (fav.logoDark) {
    root.style.setProperty('--logo-dark', fav.logoDark);
  } else {
    root.style.removeProperty('--logo-dark');
  }
  root.setAttribute('data-fav-active', '');
  setThemeColor(fav.colorPrimary ?? (dark ? fav.darkPrimary : fav.lightPrimary));

  // Compact favorite-colored favicon, served from a deterministic versioned URL.
  // The root document renders the same href during SSR.
  setFavicon(buildAppIconHref(fav.colorPrimary));
}

export function clearFavoriteBranding(): void {
  if (typeof document === 'undefined') return;
  beginBrandingUpdate();
  const root = document.documentElement;
  root.style.removeProperty('--primary');
  root.style.removeProperty('--primary-foreground');
  root.style.removeProperty('--logo-dark');
  root.removeAttribute('data-fav-active');
  setFavicon(DEFAULT_APP_ICON_HREF);
  setThemeColor(null);
}

// Backward-compat alias kept for existing call sites (theme store, etc.).
export const applyFavoriteColors = applyFavoriteBranding;

// ── Store ────────────────────────────────────────────────────────────────────

export const favoriteCorpsStore = createStore({
  context: { favorite: null as PersistedFavorite | null },
  on: {
    set: (_context, event: { input: FavoriteCorpsInput }) => ({
      favorite: toPersisted(event.input),
    }),
    clear: () => ({ favorite: null }),
    hydrate: (_context, event: { favorite: PersistedFavorite | null }) => ({
      favorite: event.favorite,
    }),
  },
});

let hydrating = false;
let notifiedFavoriteKey: string | null = null;
const favoriteKeyListeners = new Map<string, Set<() => void>>();

function notifyFavoriteKey(corpsKey: string | null): void {
  if (!corpsKey) return;
  for (const listener of favoriteKeyListeners.get(corpsKey) ?? []) listener();
}

favoriteCorpsStore.subscribe((snapshot) => {
  const fav = snapshot.context.favorite;
  if (!hydrating) persist(fav);
  if (fav) applyFavoriteBranding(fav);
  else clearFavoriteBranding();

  const nextFavoriteKey = fav?.corpsKey ?? null;
  if (nextFavoriteKey !== notifiedFavoriteKey) {
    const previousFavoriteKey = notifiedFavoriteKey;
    notifiedFavoriteKey = nextFavoriteKey;
    notifyFavoriteKey(previousFavoriteKey);
    notifyFavoriteKey(nextFavoriteKey);
  }
});

themeStore.subscribe(() => {
  const fav = favoriteCorpsStore.getSnapshot().context.favorite;
  if (fav) applyFavoriteBranding(fav);
});

// ── Hydration ─────────────────────────────────────────────────────────────────

function hydrateFavorite(): void {
  try {
    const raw = readFavoriteCookie();
    const saved = raw ? cleanFavorite(JSON.parse(raw)) : null;
    if (!saved && raw) {
      // Corrupt favorite — clear so the server head() doesn't re-read stale data.
      writeFavoriteCookie(null);
    }
    hydrating = true;
    favoriteCorpsStore.trigger.hydrate({ favorite: saved });
  } catch {
    /* ignore corrupt cookie */
  } finally {
    hydrating = false;
  }
}

if (typeof window !== 'undefined') hydrateFavorite();

// ── React hooks ──────────────────────────────────────────────────────────────

const SERVER_FAVORITE: PersistedFavorite | null = null;

const subscribeFavorite = (onChange: () => void) => {
  const sub = favoriteCorpsStore.subscribe(onChange);
  return () => sub.unsubscribe();
};

const subscribeFavoriteKey = (corpsKey: string, onChange: () => void) => {
  const listeners = favoriteKeyListeners.get(corpsKey) ?? new Set<() => void>();
  listeners.add(onChange);
  favoriteKeyListeners.set(corpsKey, listeners);
  return () => {
    listeners.delete(onChange);
    if (listeners.size === 0) favoriteKeyListeners.delete(corpsKey);
  };
};

const favoriteKeyStores = new Map<
  string,
  { subscribe: (onChange: () => void) => () => void; getSnapshot: () => boolean }
>();

function getFavoriteKeyStore(corpsKey: string) {
  const existing = favoriteKeyStores.get(corpsKey);
  if (existing) return existing;
  const store = {
    subscribe: (onChange: () => void) => subscribeFavoriteKey(corpsKey, onChange),
    getSnapshot: () => favoriteCorpsStore.getSnapshot().context.favorite?.corpsKey === corpsKey,
  };
  favoriteKeyStores.set(corpsKey, store);
  return store;
}

const subscribeFavoriteAndTheme = (onChange: () => void) => {
  const favoriteSub = favoriteCorpsStore.subscribe(onChange);
  const themeSub = themeStore.subscribe(onChange);
  return () => {
    favoriteSub.unsubscribe();
    themeSub.unsubscribe();
  };
};

export function useFavoriteCorps(): PersistedFavorite | null {
  return useSyncExternalStore(
    subscribeFavorite,
    () => favoriteCorpsStore.getSnapshot().context.favorite,
    () => SERVER_FAVORITE
  );
}

export function useIsFavorite(corpsKey: string): boolean {
  // Each corps key has a tiny external store. A favorite switch notifies only the
  // previous and next keys, so hundreds of unrelated card buttons do no work.
  const store = getFavoriteKeyStore(corpsKey);
  return useSyncExternalStore(store.subscribe, store.getSnapshot, () => false);
}

export function useFavoriteIconHref(initialHref = DEFAULT_APP_ICON_HREF): string {
  return useSyncExternalStore(
    subscribeFavorite,
    () => {
      const fav = favoriteCorpsStore.getSnapshot().context.favorite;
      return fav ? buildAppIconHref(fav.colorPrimary) : DEFAULT_APP_ICON_HREF;
    },
    () => initialHref
  );
}

export function useFavoriteThemeColor(initialColor = DARK_THEME_COLOR): string {
  return useSyncExternalStore(
    subscribeFavoriteAndTheme,
    () => {
      const fav = favoriteCorpsStore.getSnapshot().context.favorite;
      const theme = themeStore.getSnapshot().context.theme;
      if (!fav) return themeChromeColor(theme);
      const dark = theme === 'dark';
      return fav.colorPrimary ?? (dark ? fav.darkPrimary : fav.lightPrimary);
    },
    () => initialColor
  );
}
