// Apply hand-made dark-mode logo assets (corps_logo_dark_url) for corps whose
// light logo is a dark/navy mark that disappears on a dark background.
//
// Unlike the auto-recolor path (corps_logo_dark=1, which just luminance-inverts
// the light artwork via the media proxy), these are curated recolors to a
// specific brand color, stored as local /corps-logos/*.png assets:
//   - Bluecoats shield  → white   (bluecoats-dark.png)
//   - Troopers wordmark → gold     (troopers-dark.png)
//
// The asset PNGs live in public/corps-logos/ (generated by recoloring the cached
// light logo to a flat color while preserving alpha). This script is the durable,
// reproducible record of the wiring: it (1) caches each asset's bytes into
// media-cache.db under the /corps-logos/<file> key the proxy serves, and (2) sets
// corps_logo_dark_url on every corps whose corps_logo matches the mapped light
// URL (so shared-logo corps — e.g. Troopers + Troopers Legacy — are covered).
//
// Re-run after any relational-DB rebuild or a republish from another machine,
// since corps_logo_dark_url is curated data that ingest preserves but a fresh DB
// won't have. After --apply, re-emit + push the read-model (publish path) so prod
// picks it up.
//
// Usage:
//   npx tsx scripts/applyDarkLogos.ts            # dry-run
//   npx tsx scripts/applyDarkLogos.ts --apply
//
// Read-model propagation is NOT done here — run the normal publish/emit afterward.

import { createClient } from '@libsql/client';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const APPLY = process.argv.includes('--apply');

const sdkDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(sdkDir, '..');
const logoDir = path.resolve(repoRoot, 'public', 'corps-logos');
const relDbUrl = process.env.DCI_RELATIONAL_DB_URL ?? `file:${path.join(sdkDir, 'dci-relational.db')}`;
const mediaDbUrl = process.env.MEDIA_CACHE_DB_URL ?? `file:${path.join(sdkDir, 'media-cache.db')}`;

// dark asset file → the light corps_logo URL(s) it should be the dark variant of.
const DARK_LOGOS: { file: string; lightUrls: string[] }[] = [
  {
    file: 'bluecoats-dark.png', // white
    lightUrls: [
      'https://production.assets.dci.org/61f832aee12c1b07ae0ee0e2_U4-72NITblZrzChQJr_T1VnKU93o9wrY.png',
    ],
  },
  {
    file: 'troopers-dark.png', // gold
    lightUrls: [
      'https://production.assets.dci.org/63db1ffdf3587c77c40c26f4_e7iiBM79ch4cFFFPGleYxCjMd54izkiu.png',
    ],
  },
];

async function main() {
  const rel = createClient({ url: relDbUrl });
  const media = createClient({ url: mediaDbUrl });
  const nowIso = new Date().toISOString();

  for (const { file, lightUrls } of DARK_LOGOS) {
    const assetPath = path.join(logoDir, file);
    if (!fs.existsSync(assetPath)) throw new Error(`missing dark asset: ${assetPath}`);
    const key = `/corps-logos/${file}`;
    const bytes = fs.readFileSync(assetPath);

    const targets = await rel.execute({
      sql: `SELECT corps_key, name FROM corps WHERE corps_logo IN (${lightUrls.map(() => '?').join(',')})`,
      args: lightUrls,
    });
    const names = targets.rows.map((r) => r.name).join(', ');
    console.log(`\n${file} (${bytes.byteLength} bytes) → ${key}`);
    console.log(`  corps (${targets.rows.length}): ${names || '(none matched)'}`);

    if (!APPLY) continue;

    await media.execute({
      sql: `INSERT OR REPLACE INTO media_cache (url, content_type, bytes, byte_length, fetched_at)
            VALUES (?, 'image/png', ?, ?, ?)`,
      args: [key, bytes, bytes.byteLength, nowIso],
    });
    await rel.execute({
      sql: `UPDATE corps SET corps_logo_dark_url = ? WHERE corps_logo IN (${lightUrls.map(() => '?').join(',')})`,
      args: [key, ...lightUrls],
    });
  }

  console.log(APPLY ? '\nApplied. Now emit + push the read-model to publish.' : '\nDry-run — re-run with --apply.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
