// Rasterize the site favicon (a 62KB SVG illustration Satori can't render directly)
// to a small PNG and emit it as a base64 data URI module for the OG home card.
// Run: vp exec tsx sdk/scripts/genFaviconOg.ts
import sharp from 'sharp';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const svgPath = fileURLToPath(new URL('../../public/favicon.svg', import.meta.url));
const outPath = fileURLToPath(new URL('../../app/lib/og/favicon.generated.ts', import.meta.url));

const svg = readFileSync(svgPath);
const png = await sharp(svg, { density: 300 })
  .resize(256, 256, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
  .png()
  .toBuffer();
const dataUri = `data:image/png;base64,${png.toString('base64')}`;
writeFileSync(
  outPath,
  `// Generated by sdk/scripts/genFaviconOg.ts — favicon rasterized to PNG for the OG home card.\n` +
    `export const faviconPngDataUri =\n  '${dataUri}';\n`
);
console.error(`wrote favicon.generated.ts (png ${png.length} bytes, data-uri ${dataUri.length} chars)`);
