// Rasterize the brand favicons (62KB SVG illustrations Satori can't render directly)
// to small PNGs and emit them as base64 data-URI modules for the OG home cards.
// Run: vp exec tsx sdk/scripts/genFaviconOg.ts
import sharp from 'sharp';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const rasterize = async (svgRel: string) => {
  const svg = readFileSync(fileURLToPath(new URL(svgRel, import.meta.url)));
  const png = await sharp(svg, { density: 300 })
    .resize(256, 256, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  return { dataUri: `data:image/png;base64,${png.toString('base64')}`, bytes: png.length };
};

const corps = await rasterize('../../public/favicon.svg');
const jobs = await rasterize('../../public/pageantry-favicon.svg');

const outPath = fileURLToPath(new URL('../../app/lib/og/favicon.generated.ts', import.meta.url));
writeFileSync(
  outPath,
  `// Generated by sdk/scripts/genFaviconOg.ts — favicons rasterized to PNG for the OG home cards.\n` +
    `export const faviconPngDataUri =\n  '${corps.dataUri}';\n` +
    `export const pageantryFaviconPngDataUri =\n  '${jobs.dataUri}';\n`
);
console.error(`wrote favicon.generated.ts (corps ${corps.bytes}B, jobs ${jobs.bytes}B)`);
