// Codegen: derive the merch image-host allowlist from the ingested catalog.
//
// Every product image / store logo URL in merch_products/merch_stores came from a
// store WE chose to ingest (never user input), so its host is trusted — but the
// /api/media proxy must still allowlist it (SSRF). Rather than hand-maintain that
// list, we regenerate it from the catalog into a committed module that media.ts
// unions with its static CDN suffixes. EXACT hosts (not registrable suffixes) so we
// never over-trust a shared apex like amazonaws.com. Re-run on every data refresh.
//
// Usage (from sdk/):  npx tsx scripts/genMerchImageHosts.ts
import { createClient } from "@libsql/client";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync } from "node:fs";
import { loadRepoEnv } from "./scriptEnv.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SDK_DIR = resolve(__dirname, "..");
loadRepoEnv(SDK_DIR);

const DB_URL =
  process.env.DCI_RELATIONAL_DB_URL ??
  `file:${resolve(SDK_DIR, "dci-relational.db")}`;
const OUT = resolve(SDK_DIR, "..", "app", "lib", "merch-image-hosts.generated.ts");

const main = async () => {
  const db = createClient({ url: DB_URL });
  const res = await db.execute(
    `SELECT image_url AS u FROM merch_products WHERE image_url IS NOT NULL
     UNION SELECT store_logo AS u FROM merch_stores WHERE store_logo IS NOT NULL`,
  );
  const hosts = new Set<string>();
  for (const row of res.rows) {
    try {
      hosts.add(new URL(String((row as { u: unknown }).u)).host);
    } catch {
      /* skip unparseable */
    }
  }
  const sorted = [...hosts].sort();
  const body = `// AUTO-GENERATED by sdk/scripts/genMerchImageHosts.ts — do not edit by hand.
// Exact image hosts present in the ingested merch catalog (${sorted.length} hosts).
// media.ts unions these into the /api/media fetch-on-miss allowlist (SSRF-safe:
// only hosts we ingested). Re-run the generator after a merch data refresh.
export const CATALOG_IMAGE_HOSTS: readonly string[] = [
${sorted.map((h) => `  ${JSON.stringify(h)},`).join("\n")}
];
`;
  writeFileSync(OUT, body);
  console.log(`[gen] wrote ${sorted.length} hosts → ${OUT}`);
};

main().catch((err) => {
  console.error("genMerchImageHosts failed:", err);
  process.exitCode = 1;
});
