/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsRouteImport } from './routes/vs'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ShowsIndexRouteImport } from './routes/shows/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ScoresIndexRouteImport } from './routes/scores/index'
import { Route as MerchIndexRouteImport } from './routes/merch.index'
import { Route as JudgesIndexRouteImport } from './routes/judges/index'
import { Route as FantasyIndexRouteImport } from './routes/fantasy/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CorpsIndexRouteImport } from './routes/corps/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VsSlugRouteImport } from './routes/vs.$slug'
import { Route as StaffPersonIdRouteImport } from './routes/staff/$personId'
import { Route as ShopStoresRouteImport } from './routes/shop/stores'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopBookmarksRouteImport } from './routes/shop/bookmarks'
import { Route as ShopAllRouteImport } from './routes/shop/all'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as ScoresSlugRouteImport } from './routes/scores/$slug'
import { Route as PredictPaletteRouteImport } from './routes/predict/palette'
import { Route as NotifyUnsubscribeRouteImport } from './routes/notify/unsubscribe'
import { Route as MerchSplatRouteImport } from './routes/merch.$'
import { Route as JudgesJudgeIdRouteImport } from './routes/judges/$judgeId'
import { Route as JobsTermsRouteImport } from './routes/jobs/terms'
import { Route as JobsTalentRouteImport } from './routes/jobs/talent'
import { Route as JobsPrivacyRouteImport } from './routes/jobs/privacy'
import { Route as JobsPostRouteImport } from './routes/jobs/post'
import { Route as JobsOnboardRouteImport } from './routes/jobs/onboard'
import { Route as JobsMeRouteImport } from './routes/jobs/me'
import { Route as JobsGuidelinesRouteImport } from './routes/jobs/guidelines'
import { Route as JobsCategoriesRouteImport } from './routes/jobs/categories'
import { Route as JobsBoardRouteImport } from './routes/jobs/board'
import { Route as JobsAdminRouteImport } from './routes/jobs/admin'
import { Route as JobsJobSlugRouteImport } from './routes/jobs/$jobSlug'
import { Route as FantasyQuizAdminRouteImport } from './routes/fantasy/quiz-admin'
import { Route as FantasyCreateRouteImport } from './routes/fantasy/create'
import { Route as DevFreeFormSpikeRouteImport } from './routes/dev/free-form-spike'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminProfileClaimsRouteImport } from './routes/admin/profile-claims'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminIdentityRouteImport } from './routes/admin/identity'
import { Route as AdminCorpsColorsRouteImport } from './routes/admin/corps-colors'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as FantasySlugIndexRouteImport } from './routes/fantasy/$slug/index'
import { Route as EventsYearSlugIndexRouteImport } from './routes/events/$yearSlug/index'
import { Route as ShowsSlugSeasonRouteImport } from './routes/shows/$slug.$season'
import { Route as ShopGroupStoreIdRouteImport } from './routes/shop/group/$storeId'
import { Route as ShopCategoryCatRouteImport } from './routes/shop/category/$cat'
import { Route as JobsProfileSlugRouteImport } from './routes/jobs/profile/$slug'
import { Route as JobsCSlugRouteImport } from './routes/jobs/c/$slug'
import { Route as FantasyJoinTokenRouteImport } from './routes/fantasy/join/$token'
import { Route as FantasySlugStandingsRouteImport } from './routes/fantasy/$slug/standings'
import { Route as FantasySlugQuizRouteImport } from './routes/fantasy/$slug/quiz'
import { Route as FantasySlugDraftRouteImport } from './routes/fantasy/$slug/draft'
import { Route as CorpsSlugChar123SeasonChar125RouteImport } from './routes/corps/$slug.{-$season}'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as AdminFantasyTestLabRouteImport } from './routes/admin/fantasy/test-lab'
import { Route as AdminFantasyQuizRouteImport } from './routes/admin/fantasy/quiz'
import { Route as AdminFantasyLeaguesRouteImport } from './routes/admin/fantasy/leagues'
import { Route as EventsYearSlugSlugPredictionRouteImport } from './routes/events/$yearSlug/$slug/prediction'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as RobotsDottxtServerRouteImport } from './routes/robots[.]txt'
import { ServerRoute as FaviconDoticoServerRouteImport } from './routes/favicon[.]ico'
import { ServerRoute as AppIconDotsvgServerRouteImport } from './routes/app-icon[.]svg'
import { ServerRoute as ReadModelStaffServerRouteImport } from './routes/read-model/staff'
import { ServerRoute as ReadModelManifestDotjsonServerRouteImport } from './routes/read-model/manifest[.]json'
import { ServerRoute as ReadModelJudgesServerRouteImport } from './routes/read-model/judges'
import { ServerRoute as ReadModelEventsServerRouteImport } from './routes/read-model/events'
import { ServerRoute as ReadModelCorpsServerRouteImport } from './routes/read-model/corps'
import { ServerRoute as ApiVersionServerRouteImport } from './routes/api/version'
import { ServerRoute as ApiMediaServerRouteImport } from './routes/api/media'
import { ServerRoute as ApiCollectServerRouteImport } from './routes/api/collect'
import { ServerRoute as ReadModelRecapsSlugServerRouteImport } from './routes/read-model/recaps/$slug'
import { ServerRoute as ApiShowMediaIdServerRouteImport } from './routes/api/show-media/$id'
import { ServerRoute as ApiOgJobsHomeServerRouteImport } from './routes/api/og/jobs-home'
import { ServerRoute as ApiOgHomeServerRouteImport } from './routes/api/og/home'
import { ServerRoute as ApiJobsStripeWebhookServerRouteImport } from './routes/api/jobs/stripe-webhook'
import { ServerRoute as ApiFantasyStripeWebhookServerRouteImport } from './routes/api/fantasy/stripe-webhook'
import { ServerRoute as ApiFantasyMediaIdServerRouteImport } from './routes/api/fantasy-media/$id'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiOgScoreSlugServerRouteImport } from './routes/api/og/score/$slug'
import { ServerRoute as ApiFantasyJobsRecomputeServerRouteImport } from './routes/api/fantasy/jobs/recompute'
import { ServerRoute as ApiFantasyJobsDispatchServerRouteImport } from './routes/api/fantasy/jobs/dispatch'
import { ServerRoute as ApiOgShowSlugSeasonServerRouteImport } from './routes/api/og/show/$slug.$season'
import { ServerRoute as ApiFantasyDraftLeagueIdStreamServerRouteImport } from './routes/api/fantasy/draft/$leagueId/stream'

const rootServerRouteImport = createServerRootRoute()

const VsRoute = VsRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresIndexRoute = ScoresIndexRouteImport.update({
  id: '/scores/',
  path: '/scores/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchIndexRoute = MerchIndexRouteImport.update({
  id: '/merch/',
  path: '/merch/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIndexRoute = JudgesIndexRouteImport.update({
  id: '/judges/',
  path: '/judges/',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyIndexRoute = FantasyIndexRouteImport.update({
  id: '/fantasy/',
  path: '/fantasy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpsIndexRoute = CorpsIndexRouteImport.update({
  id: '/corps/',
  path: '/corps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSlugRoute = VsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VsRoute,
} as any)
const StaffPersonIdRoute = StaffPersonIdRouteImport.update({
  id: '/staff/$personId',
  path: '/staff/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStoresRoute = ShopStoresRouteImport.update({
  id: '/shop/stores',
  path: '/shop/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBookmarksRoute = ShopBookmarksRouteImport.update({
  id: '/shop/bookmarks',
  path: '/shop/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAllRoute = ShopAllRouteImport.update({
  id: '/shop/all',
  path: '/shop/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresSlugRoute = ScoresSlugRouteImport.update({
  id: '/scores/$slug',
  path: '/scores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictPaletteRoute = PredictPaletteRouteImport.update({
  id: '/predict/palette',
  path: '/predict/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyUnsubscribeRoute = NotifyUnsubscribeRouteImport.update({
  id: '/notify/unsubscribe',
  path: '/notify/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchSplatRoute = MerchSplatRouteImport.update({
  id: '/merch/$',
  path: '/merch/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesJudgeIdRoute = JudgesJudgeIdRouteImport.update({
  id: '/judges/$judgeId',
  path: '/judges/$judgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsTermsRoute = JobsTermsRouteImport.update({
  id: '/jobs/terms',
  path: '/jobs/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsTalentRoute = JobsTalentRouteImport.update({
  id: '/jobs/talent',
  path: '/jobs/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsPrivacyRoute = JobsPrivacyRouteImport.update({
  id: '/jobs/privacy',
  path: '/jobs/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsPostRoute = JobsPostRouteImport.update({
  id: '/jobs/post',
  path: '/jobs/post',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsOnboardRoute = JobsOnboardRouteImport.update({
  id: '/jobs/onboard',
  path: '/jobs/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsMeRoute = JobsMeRouteImport.update({
  id: '/jobs/me',
  path: '/jobs/me',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsGuidelinesRoute = JobsGuidelinesRouteImport.update({
  id: '/jobs/guidelines',
  path: '/jobs/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCategoriesRoute = JobsCategoriesRouteImport.update({
  id: '/jobs/categories',
  path: '/jobs/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsBoardRoute = JobsBoardRouteImport.update({
  id: '/jobs/board',
  path: '/jobs/board',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsAdminRoute = JobsAdminRouteImport.update({
  id: '/jobs/admin',
  path: '/jobs/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobSlugRoute = JobsJobSlugRouteImport.update({
  id: '/jobs/$jobSlug',
  path: '/jobs/$jobSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyQuizAdminRoute = FantasyQuizAdminRouteImport.update({
  id: '/fantasy/quiz-admin',
  path: '/fantasy/quiz-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyCreateRoute = FantasyCreateRouteImport.update({
  id: '/fantasy/create',
  path: '/fantasy/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFreeFormSpikeRoute = DevFreeFormSpikeRouteImport.update({
  id: '/dev/free-form-spike',
  path: '/dev/free-form-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileClaimsRoute = AdminProfileClaimsRouteImport.update({
  id: '/admin/profile-claims',
  path: '/admin/profile-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdentityRoute = AdminIdentityRouteImport.update({
  id: '/admin/identity',
  path: '/admin/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorpsColorsRoute = AdminCorpsColorsRouteImport.update({
  id: '/admin/corps-colors',
  path: '/admin/corps-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasySlugIndexRoute = FantasySlugIndexRouteImport.update({
  id: '/fantasy/$slug/',
  path: '/fantasy/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsYearSlugIndexRoute = EventsYearSlugIndexRouteImport.update({
  id: '/events/$yearSlug/',
  path: '/events/$yearSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsSlugSeasonRoute = ShowsSlugSeasonRouteImport.update({
  id: '/shows/$slug/$season',
  path: '/shows/$slug/$season',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopGroupStoreIdRoute = ShopGroupStoreIdRouteImport.update({
  id: '/shop/group/$storeId',
  path: '/shop/group/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryCatRoute = ShopCategoryCatRouteImport.update({
  id: '/shop/category/$cat',
  path: '/shop/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsProfileSlugRoute = JobsProfileSlugRouteImport.update({
  id: '/jobs/profile/$slug',
  path: '/jobs/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCSlugRoute = JobsCSlugRouteImport.update({
  id: '/jobs/c/$slug',
  path: '/jobs/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyJoinTokenRoute = FantasyJoinTokenRouteImport.update({
  id: '/fantasy/join/$token',
  path: '/fantasy/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasySlugStandingsRoute = FantasySlugStandingsRouteImport.update({
  id: '/fantasy/$slug/standings',
  path: '/fantasy/$slug/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasySlugQuizRoute = FantasySlugQuizRouteImport.update({
  id: '/fantasy/$slug/quiz',
  path: '/fantasy/$slug/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasySlugDraftRoute = FantasySlugDraftRouteImport.update({
  id: '/fantasy/$slug/draft',
  path: '/fantasy/$slug/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpsSlugChar123SeasonChar125Route =
  CorpsSlugChar123SeasonChar125RouteImport.update({
    id: '/corps/$slug/{-$season}',
    path: '/corps/$slug/{-$season}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminFantasyTestLabRoute = AdminFantasyTestLabRouteImport.update({
  id: '/admin/fantasy/test-lab',
  path: '/admin/fantasy/test-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFantasyQuizRoute = AdminFantasyQuizRouteImport.update({
  id: '/admin/fantasy/quiz',
  path: '/admin/fantasy/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFantasyLeaguesRoute = AdminFantasyLeaguesRouteImport.update({
  id: '/admin/fantasy/leagues',
  path: '/admin/fantasy/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsYearSlugSlugPredictionRoute =
  EventsYearSlugSlugPredictionRouteImport.update({
    id: '/events/$yearSlug/$slug/prediction',
    path: '/events/$yearSlug/$slug/prediction',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const RobotsDottxtServerRoute = RobotsDottxtServerRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootServerRouteImport,
} as any)
const FaviconDoticoServerRoute = FaviconDoticoServerRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AppIconDotsvgServerRoute = AppIconDotsvgServerRouteImport.update({
  id: '/app-icon.svg',
  path: '/app-icon.svg',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ReadModelStaffServerRoute = ReadModelStaffServerRouteImport.update({
  id: '/read-model/staff',
  path: '/read-model/staff',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ReadModelManifestDotjsonServerRoute =
  ReadModelManifestDotjsonServerRouteImport.update({
    id: '/read-model/manifest.json',
    path: '/read-model/manifest.json',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ReadModelJudgesServerRoute = ReadModelJudgesServerRouteImport.update({
  id: '/read-model/judges',
  path: '/read-model/judges',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ReadModelEventsServerRoute = ReadModelEventsServerRouteImport.update({
  id: '/read-model/events',
  path: '/read-model/events',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ReadModelCorpsServerRoute = ReadModelCorpsServerRouteImport.update({
  id: '/read-model/corps',
  path: '/read-model/corps',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiVersionServerRoute = ApiVersionServerRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMediaServerRoute = ApiMediaServerRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCollectServerRoute = ApiCollectServerRouteImport.update({
  id: '/api/collect',
  path: '/api/collect',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ReadModelRecapsSlugServerRoute =
  ReadModelRecapsSlugServerRouteImport.update({
    id: '/read-model/recaps/$slug',
    path: '/read-model/recaps/$slug',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiShowMediaIdServerRoute = ApiShowMediaIdServerRouteImport.update({
  id: '/api/show-media/$id',
  path: '/api/show-media/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOgJobsHomeServerRoute = ApiOgJobsHomeServerRouteImport.update({
  id: '/api/og/jobs-home',
  path: '/api/og/jobs-home',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOgHomeServerRoute = ApiOgHomeServerRouteImport.update({
  id: '/api/og/home',
  path: '/api/og/home',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiJobsStripeWebhookServerRoute =
  ApiJobsStripeWebhookServerRouteImport.update({
    id: '/api/jobs/stripe-webhook',
    path: '/api/jobs/stripe-webhook',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFantasyStripeWebhookServerRoute =
  ApiFantasyStripeWebhookServerRouteImport.update({
    id: '/api/fantasy/stripe-webhook',
    path: '/api/fantasy/stripe-webhook',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFantasyMediaIdServerRoute = ApiFantasyMediaIdServerRouteImport.update({
  id: '/api/fantasy-media/$id',
  path: '/api/fantasy-media/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOgScoreSlugServerRoute = ApiOgScoreSlugServerRouteImport.update({
  id: '/api/og/score/$slug',
  path: '/api/og/score/$slug',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFantasyJobsRecomputeServerRoute =
  ApiFantasyJobsRecomputeServerRouteImport.update({
    id: '/api/fantasy/jobs/recompute',
    path: '/api/fantasy/jobs/recompute',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFantasyJobsDispatchServerRoute =
  ApiFantasyJobsDispatchServerRouteImport.update({
    id: '/api/fantasy/jobs/dispatch',
    path: '/api/fantasy/jobs/dispatch',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiOgShowSlugSeasonServerRoute =
  ApiOgShowSlugSeasonServerRouteImport.update({
    id: '/api/og/show/$slug/$season',
    path: '/api/og/show/$slug/$season',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFantasyDraftLeagueIdStreamServerRoute =
  ApiFantasyDraftLeagueIdStreamServerRouteImport.update({
    id: '/api/fantasy/draft/$leagueId/stream',
    path: '/api/fantasy/draft/$leagueId/stream',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/vs': typeof VsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/profile-claims': typeof AdminProfileClaimsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/quiz-admin': typeof FantasyQuizAdminRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs/admin': typeof JobsAdminRoute
  '/jobs/board': typeof JobsBoardRoute
  '/jobs/categories': typeof JobsCategoriesRoute
  '/jobs/guidelines': typeof JobsGuidelinesRoute
  '/jobs/me': typeof JobsMeRoute
  '/jobs/onboard': typeof JobsOnboardRoute
  '/jobs/post': typeof JobsPostRoute
  '/jobs/privacy': typeof JobsPrivacyRoute
  '/jobs/talent': typeof JobsTalentRoute
  '/jobs/terms': typeof JobsTermsRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/notify/unsubscribe': typeof NotifyUnsubscribeRoute
  '/predict/palette': typeof PredictPaletteRoute
  '/scores/$slug': typeof ScoresSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/vs/$slug': typeof VsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/corps': typeof CorpsIndexRoute
  '/events': typeof EventsIndexRoute
  '/fantasy': typeof FantasyIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/merch': typeof MerchIndexRoute
  '/scores': typeof ScoresIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shows': typeof ShowsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/fantasy/leagues': typeof AdminFantasyLeaguesRoute
  '/admin/fantasy/quiz': typeof AdminFantasyQuizRoute
  '/admin/fantasy/test-lab': typeof AdminFantasyTestLabRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/fantasy/$slug/draft': typeof FantasySlugDraftRoute
  '/fantasy/$slug/quiz': typeof FantasySlugQuizRoute
  '/fantasy/$slug/standings': typeof FantasySlugStandingsRoute
  '/fantasy/join/$token': typeof FantasyJoinTokenRoute
  '/jobs/c/$slug': typeof JobsCSlugRoute
  '/jobs/profile/$slug': typeof JobsProfileSlugRoute
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug': typeof EventsYearSlugIndexRoute
  '/fantasy/$slug': typeof FantasySlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/vs': typeof VsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/profile-claims': typeof AdminProfileClaimsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/quiz-admin': typeof FantasyQuizAdminRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs/admin': typeof JobsAdminRoute
  '/jobs/board': typeof JobsBoardRoute
  '/jobs/categories': typeof JobsCategoriesRoute
  '/jobs/guidelines': typeof JobsGuidelinesRoute
  '/jobs/me': typeof JobsMeRoute
  '/jobs/onboard': typeof JobsOnboardRoute
  '/jobs/post': typeof JobsPostRoute
  '/jobs/privacy': typeof JobsPrivacyRoute
  '/jobs/talent': typeof JobsTalentRoute
  '/jobs/terms': typeof JobsTermsRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/notify/unsubscribe': typeof NotifyUnsubscribeRoute
  '/predict/palette': typeof PredictPaletteRoute
  '/scores/$slug': typeof ScoresSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/vs/$slug': typeof VsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/corps': typeof CorpsIndexRoute
  '/events': typeof EventsIndexRoute
  '/fantasy': typeof FantasyIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/merch': typeof MerchIndexRoute
  '/scores': typeof ScoresIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shows': typeof ShowsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/fantasy/leagues': typeof AdminFantasyLeaguesRoute
  '/admin/fantasy/quiz': typeof AdminFantasyQuizRoute
  '/admin/fantasy/test-lab': typeof AdminFantasyTestLabRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/fantasy/$slug/draft': typeof FantasySlugDraftRoute
  '/fantasy/$slug/quiz': typeof FantasySlugQuizRoute
  '/fantasy/$slug/standings': typeof FantasySlugStandingsRoute
  '/fantasy/join/$token': typeof FantasyJoinTokenRoute
  '/jobs/c/$slug': typeof JobsCSlugRoute
  '/jobs/profile/$slug': typeof JobsProfileSlugRoute
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug': typeof EventsYearSlugIndexRoute
  '/fantasy/$slug': typeof FantasySlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/vs': typeof VsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/profile-claims': typeof AdminProfileClaimsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/fantasy/create': typeof FantasyCreateRoute
  '/fantasy/quiz-admin': typeof FantasyQuizAdminRoute
  '/jobs/$jobSlug': typeof JobsJobSlugRoute
  '/jobs/admin': typeof JobsAdminRoute
  '/jobs/board': typeof JobsBoardRoute
  '/jobs/categories': typeof JobsCategoriesRoute
  '/jobs/guidelines': typeof JobsGuidelinesRoute
  '/jobs/me': typeof JobsMeRoute
  '/jobs/onboard': typeof JobsOnboardRoute
  '/jobs/post': typeof JobsPostRoute
  '/jobs/privacy': typeof JobsPrivacyRoute
  '/jobs/talent': typeof JobsTalentRoute
  '/jobs/terms': typeof JobsTermsRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/notify/unsubscribe': typeof NotifyUnsubscribeRoute
  '/predict/palette': typeof PredictPaletteRoute
  '/scores/$slug': typeof ScoresSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/vs/$slug': typeof VsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/corps/': typeof CorpsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/fantasy/': typeof FantasyIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/merch/': typeof MerchIndexRoute
  '/scores/': typeof ScoresIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/fantasy/leagues': typeof AdminFantasyLeaguesRoute
  '/admin/fantasy/quiz': typeof AdminFantasyQuizRoute
  '/admin/fantasy/test-lab': typeof AdminFantasyTestLabRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/fantasy/$slug/draft': typeof FantasySlugDraftRoute
  '/fantasy/$slug/quiz': typeof FantasySlugQuizRoute
  '/fantasy/$slug/standings': typeof FantasySlugStandingsRoute
  '/fantasy/join/$token': typeof FantasyJoinTokenRoute
  '/jobs/c/$slug': typeof JobsCSlugRoute
  '/jobs/profile/$slug': typeof JobsProfileSlugRoute
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug/': typeof EventsYearSlugIndexRoute
  '/fantasy/$slug/': typeof FantasySlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/rankings'
    | '/terms-of-service'
    | '/vs'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/corps-colors'
    | '/admin/identity'
    | '/admin/jobs'
    | '/admin/profile-claims'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/dev/free-form-spike'
    | '/fantasy/create'
    | '/fantasy/quiz-admin'
    | '/jobs/$jobSlug'
    | '/jobs/admin'
    | '/jobs/board'
    | '/jobs/categories'
    | '/jobs/guidelines'
    | '/jobs/me'
    | '/jobs/onboard'
    | '/jobs/post'
    | '/jobs/privacy'
    | '/jobs/talent'
    | '/jobs/terms'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/notify/unsubscribe'
    | '/predict/palette'
    | '/scores/$slug'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/vs/$slug'
    | '/admin'
    | '/corps'
    | '/events'
    | '/fantasy'
    | '/judges'
    | '/merch'
    | '/scores'
    | '/shop'
    | '/shows'
    | '/staff'
    | '/admin/fantasy/leagues'
    | '/admin/fantasy/quiz'
    | '/admin/fantasy/test-lab'
    | '/admin/users/$id'
    | '/corps/$slug/{-$season}'
    | '/fantasy/$slug/draft'
    | '/fantasy/$slug/quiz'
    | '/fantasy/$slug/standings'
    | '/fantasy/join/$token'
    | '/jobs/c/$slug'
    | '/jobs/profile/$slug'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug'
    | '/fantasy/$slug'
    | '/events/$yearSlug/$slug/prediction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/rankings'
    | '/terms-of-service'
    | '/vs'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/corps-colors'
    | '/admin/identity'
    | '/admin/jobs'
    | '/admin/profile-claims'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/dev/free-form-spike'
    | '/fantasy/create'
    | '/fantasy/quiz-admin'
    | '/jobs/$jobSlug'
    | '/jobs/admin'
    | '/jobs/board'
    | '/jobs/categories'
    | '/jobs/guidelines'
    | '/jobs/me'
    | '/jobs/onboard'
    | '/jobs/post'
    | '/jobs/privacy'
    | '/jobs/talent'
    | '/jobs/terms'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/notify/unsubscribe'
    | '/predict/palette'
    | '/scores/$slug'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/vs/$slug'
    | '/admin'
    | '/corps'
    | '/events'
    | '/fantasy'
    | '/judges'
    | '/merch'
    | '/scores'
    | '/shop'
    | '/shows'
    | '/staff'
    | '/admin/fantasy/leagues'
    | '/admin/fantasy/quiz'
    | '/admin/fantasy/test-lab'
    | '/admin/users/$id'
    | '/corps/$slug/{-$season}'
    | '/fantasy/$slug/draft'
    | '/fantasy/$slug/quiz'
    | '/fantasy/$slug/standings'
    | '/fantasy/join/$token'
    | '/jobs/c/$slug'
    | '/jobs/profile/$slug'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug'
    | '/fantasy/$slug'
    | '/events/$yearSlug/$slug/prediction'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/rankings'
    | '/terms-of-service'
    | '/vs'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/corps-colors'
    | '/admin/identity'
    | '/admin/jobs'
    | '/admin/profile-claims'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/dev/free-form-spike'
    | '/fantasy/create'
    | '/fantasy/quiz-admin'
    | '/jobs/$jobSlug'
    | '/jobs/admin'
    | '/jobs/board'
    | '/jobs/categories'
    | '/jobs/guidelines'
    | '/jobs/me'
    | '/jobs/onboard'
    | '/jobs/post'
    | '/jobs/privacy'
    | '/jobs/talent'
    | '/jobs/terms'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/notify/unsubscribe'
    | '/predict/palette'
    | '/scores/$slug'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/vs/$slug'
    | '/admin/'
    | '/corps/'
    | '/events/'
    | '/fantasy/'
    | '/judges/'
    | '/merch/'
    | '/scores/'
    | '/shop/'
    | '/shows/'
    | '/staff/'
    | '/admin/fantasy/leagues'
    | '/admin/fantasy/quiz'
    | '/admin/fantasy/test-lab'
    | '/admin/users/$id'
    | '/corps/$slug/{-$season}'
    | '/fantasy/$slug/draft'
    | '/fantasy/$slug/quiz'
    | '/fantasy/$slug/standings'
    | '/fantasy/join/$token'
    | '/jobs/c/$slug'
    | '/jobs/profile/$slug'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug/'
    | '/fantasy/$slug/'
    | '/events/$yearSlug/$slug/prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RankingsRoute: typeof RankingsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  VsRoute: typeof VsRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCorpsColorsRoute: typeof AdminCorpsColorsRoute
  AdminIdentityRoute: typeof AdminIdentityRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminProfileClaimsRoute: typeof AdminProfileClaimsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  DevFreeFormSpikeRoute: typeof DevFreeFormSpikeRoute
  FantasyCreateRoute: typeof FantasyCreateRoute
  FantasyQuizAdminRoute: typeof FantasyQuizAdminRoute
  JobsJobSlugRoute: typeof JobsJobSlugRoute
  JobsAdminRoute: typeof JobsAdminRoute
  JobsBoardRoute: typeof JobsBoardRoute
  JobsCategoriesRoute: typeof JobsCategoriesRoute
  JobsGuidelinesRoute: typeof JobsGuidelinesRoute
  JobsMeRoute: typeof JobsMeRoute
  JobsOnboardRoute: typeof JobsOnboardRoute
  JobsPostRoute: typeof JobsPostRoute
  JobsPrivacyRoute: typeof JobsPrivacyRoute
  JobsTalentRoute: typeof JobsTalentRoute
  JobsTermsRoute: typeof JobsTermsRoute
  JudgesJudgeIdRoute: typeof JudgesJudgeIdRoute
  MerchSplatRoute: typeof MerchSplatRoute
  NotifyUnsubscribeRoute: typeof NotifyUnsubscribeRoute
  PredictPaletteRoute: typeof PredictPaletteRoute
  ScoresSlugRoute: typeof ScoresSlugRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopAllRoute: typeof ShopAllRoute
  ShopBookmarksRoute: typeof ShopBookmarksRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopStoresRoute: typeof ShopStoresRoute
  StaffPersonIdRoute: typeof StaffPersonIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CorpsIndexRoute: typeof CorpsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FantasyIndexRoute: typeof FantasyIndexRoute
  JudgesIndexRoute: typeof JudgesIndexRoute
  MerchIndexRoute: typeof MerchIndexRoute
  ScoresIndexRoute: typeof ScoresIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  AdminFantasyLeaguesRoute: typeof AdminFantasyLeaguesRoute
  AdminFantasyQuizRoute: typeof AdminFantasyQuizRoute
  AdminFantasyTestLabRoute: typeof AdminFantasyTestLabRoute
  CorpsSlugChar123SeasonChar125Route: typeof CorpsSlugChar123SeasonChar125Route
  FantasySlugDraftRoute: typeof FantasySlugDraftRoute
  FantasySlugQuizRoute: typeof FantasySlugQuizRoute
  FantasySlugStandingsRoute: typeof FantasySlugStandingsRoute
  FantasyJoinTokenRoute: typeof FantasyJoinTokenRoute
  JobsCSlugRoute: typeof JobsCSlugRoute
  JobsProfileSlugRoute: typeof JobsProfileSlugRoute
  ShopCategoryCatRoute: typeof ShopCategoryCatRoute
  ShopGroupStoreIdRoute: typeof ShopGroupStoreIdRoute
  ShowsSlugSeasonRoute: typeof ShowsSlugSeasonRoute
  EventsYearSlugIndexRoute: typeof EventsYearSlugIndexRoute
  FantasySlugIndexRoute: typeof FantasySlugIndexRoute
  EventsYearSlugSlugPredictionRoute: typeof EventsYearSlugSlugPredictionRoute
}
export interface FileServerRoutesByFullPath {
  '/app-icon.svg': typeof AppIconDotsvgServerRoute
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/collect': typeof ApiCollectServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/version': typeof ApiVersionServerRoute
  '/read-model/corps': typeof ReadModelCorpsServerRoute
  '/read-model/events': typeof ReadModelEventsServerRoute
  '/read-model/judges': typeof ReadModelJudgesServerRoute
  '/read-model/manifest.json': typeof ReadModelManifestDotjsonServerRoute
  '/read-model/staff': typeof ReadModelStaffServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/fantasy-media/$id': typeof ApiFantasyMediaIdServerRoute
  '/api/fantasy/stripe-webhook': typeof ApiFantasyStripeWebhookServerRoute
  '/api/jobs/stripe-webhook': typeof ApiJobsStripeWebhookServerRoute
  '/api/og/home': typeof ApiOgHomeServerRoute
  '/api/og/jobs-home': typeof ApiOgJobsHomeServerRoute
  '/api/show-media/$id': typeof ApiShowMediaIdServerRoute
  '/read-model/recaps/$slug': typeof ReadModelRecapsSlugServerRoute
  '/api/fantasy/jobs/dispatch': typeof ApiFantasyJobsDispatchServerRoute
  '/api/fantasy/jobs/recompute': typeof ApiFantasyJobsRecomputeServerRoute
  '/api/og/score/$slug': typeof ApiOgScoreSlugServerRoute
  '/api/fantasy/draft/$leagueId/stream': typeof ApiFantasyDraftLeagueIdStreamServerRoute
  '/api/og/show/$slug/$season': typeof ApiOgShowSlugSeasonServerRoute
}
export interface FileServerRoutesByTo {
  '/app-icon.svg': typeof AppIconDotsvgServerRoute
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/collect': typeof ApiCollectServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/version': typeof ApiVersionServerRoute
  '/read-model/corps': typeof ReadModelCorpsServerRoute
  '/read-model/events': typeof ReadModelEventsServerRoute
  '/read-model/judges': typeof ReadModelJudgesServerRoute
  '/read-model/manifest.json': typeof ReadModelManifestDotjsonServerRoute
  '/read-model/staff': typeof ReadModelStaffServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/fantasy-media/$id': typeof ApiFantasyMediaIdServerRoute
  '/api/fantasy/stripe-webhook': typeof ApiFantasyStripeWebhookServerRoute
  '/api/jobs/stripe-webhook': typeof ApiJobsStripeWebhookServerRoute
  '/api/og/home': typeof ApiOgHomeServerRoute
  '/api/og/jobs-home': typeof ApiOgJobsHomeServerRoute
  '/api/show-media/$id': typeof ApiShowMediaIdServerRoute
  '/read-model/recaps/$slug': typeof ReadModelRecapsSlugServerRoute
  '/api/fantasy/jobs/dispatch': typeof ApiFantasyJobsDispatchServerRoute
  '/api/fantasy/jobs/recompute': typeof ApiFantasyJobsRecomputeServerRoute
  '/api/og/score/$slug': typeof ApiOgScoreSlugServerRoute
  '/api/fantasy/draft/$leagueId/stream': typeof ApiFantasyDraftLeagueIdStreamServerRoute
  '/api/og/show/$slug/$season': typeof ApiOgShowSlugSeasonServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/app-icon.svg': typeof AppIconDotsvgServerRoute
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/collect': typeof ApiCollectServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/version': typeof ApiVersionServerRoute
  '/read-model/corps': typeof ReadModelCorpsServerRoute
  '/read-model/events': typeof ReadModelEventsServerRoute
  '/read-model/judges': typeof ReadModelJudgesServerRoute
  '/read-model/manifest.json': typeof ReadModelManifestDotjsonServerRoute
  '/read-model/staff': typeof ReadModelStaffServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/fantasy-media/$id': typeof ApiFantasyMediaIdServerRoute
  '/api/fantasy/stripe-webhook': typeof ApiFantasyStripeWebhookServerRoute
  '/api/jobs/stripe-webhook': typeof ApiJobsStripeWebhookServerRoute
  '/api/og/home': typeof ApiOgHomeServerRoute
  '/api/og/jobs-home': typeof ApiOgJobsHomeServerRoute
  '/api/show-media/$id': typeof ApiShowMediaIdServerRoute
  '/read-model/recaps/$slug': typeof ReadModelRecapsSlugServerRoute
  '/api/fantasy/jobs/dispatch': typeof ApiFantasyJobsDispatchServerRoute
  '/api/fantasy/jobs/recompute': typeof ApiFantasyJobsRecomputeServerRoute
  '/api/og/score/$slug': typeof ApiOgScoreSlugServerRoute
  '/api/fantasy/draft/$leagueId/stream': typeof ApiFantasyDraftLeagueIdStreamServerRoute
  '/api/og/show/$slug/$season': typeof ApiOgShowSlugSeasonServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/app-icon.svg'
    | '/favicon.ico'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/collect'
    | '/api/media'
    | '/api/version'
    | '/read-model/corps'
    | '/read-model/events'
    | '/read-model/judges'
    | '/read-model/manifest.json'
    | '/read-model/staff'
    | '/api/auth/$'
    | '/api/fantasy-media/$id'
    | '/api/fantasy/stripe-webhook'
    | '/api/jobs/stripe-webhook'
    | '/api/og/home'
    | '/api/og/jobs-home'
    | '/api/show-media/$id'
    | '/read-model/recaps/$slug'
    | '/api/fantasy/jobs/dispatch'
    | '/api/fantasy/jobs/recompute'
    | '/api/og/score/$slug'
    | '/api/fantasy/draft/$leagueId/stream'
    | '/api/og/show/$slug/$season'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/app-icon.svg'
    | '/favicon.ico'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/collect'
    | '/api/media'
    | '/api/version'
    | '/read-model/corps'
    | '/read-model/events'
    | '/read-model/judges'
    | '/read-model/manifest.json'
    | '/read-model/staff'
    | '/api/auth/$'
    | '/api/fantasy-media/$id'
    | '/api/fantasy/stripe-webhook'
    | '/api/jobs/stripe-webhook'
    | '/api/og/home'
    | '/api/og/jobs-home'
    | '/api/show-media/$id'
    | '/read-model/recaps/$slug'
    | '/api/fantasy/jobs/dispatch'
    | '/api/fantasy/jobs/recompute'
    | '/api/og/score/$slug'
    | '/api/fantasy/draft/$leagueId/stream'
    | '/api/og/show/$slug/$season'
  id:
    | '__root__'
    | '/app-icon.svg'
    | '/favicon.ico'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/collect'
    | '/api/media'
    | '/api/version'
    | '/read-model/corps'
    | '/read-model/events'
    | '/read-model/judges'
    | '/read-model/manifest.json'
    | '/read-model/staff'
    | '/api/auth/$'
    | '/api/fantasy-media/$id'
    | '/api/fantasy/stripe-webhook'
    | '/api/jobs/stripe-webhook'
    | '/api/og/home'
    | '/api/og/jobs-home'
    | '/api/show-media/$id'
    | '/read-model/recaps/$slug'
    | '/api/fantasy/jobs/dispatch'
    | '/api/fantasy/jobs/recompute'
    | '/api/og/score/$slug'
    | '/api/fantasy/draft/$leagueId/stream'
    | '/api/og/show/$slug/$season'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AppIconDotsvgServerRoute: typeof AppIconDotsvgServerRoute
  FaviconDoticoServerRoute: typeof FaviconDoticoServerRoute
  RobotsDottxtServerRoute: typeof RobotsDottxtServerRoute
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
  ApiCollectServerRoute: typeof ApiCollectServerRoute
  ApiMediaServerRoute: typeof ApiMediaServerRoute
  ApiVersionServerRoute: typeof ApiVersionServerRoute
  ReadModelCorpsServerRoute: typeof ReadModelCorpsServerRoute
  ReadModelEventsServerRoute: typeof ReadModelEventsServerRoute
  ReadModelJudgesServerRoute: typeof ReadModelJudgesServerRoute
  ReadModelManifestDotjsonServerRoute: typeof ReadModelManifestDotjsonServerRoute
  ReadModelStaffServerRoute: typeof ReadModelStaffServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiFantasyMediaIdServerRoute: typeof ApiFantasyMediaIdServerRoute
  ApiFantasyStripeWebhookServerRoute: typeof ApiFantasyStripeWebhookServerRoute
  ApiJobsStripeWebhookServerRoute: typeof ApiJobsStripeWebhookServerRoute
  ApiOgHomeServerRoute: typeof ApiOgHomeServerRoute
  ApiOgJobsHomeServerRoute: typeof ApiOgJobsHomeServerRoute
  ApiShowMediaIdServerRoute: typeof ApiShowMediaIdServerRoute
  ReadModelRecapsSlugServerRoute: typeof ReadModelRecapsSlugServerRoute
  ApiFantasyJobsDispatchServerRoute: typeof ApiFantasyJobsDispatchServerRoute
  ApiFantasyJobsRecomputeServerRoute: typeof ApiFantasyJobsRecomputeServerRoute
  ApiOgScoreSlugServerRoute: typeof ApiOgScoreSlugServerRoute
  ApiFantasyDraftLeagueIdStreamServerRoute: typeof ApiFantasyDraftLeagueIdStreamServerRoute
  ApiOgShowSlugSeasonServerRoute: typeof ApiOgShowSlugSeasonServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs': {
      id: '/vs'
      path: '/vs'
      fullPath: '/vs'
      preLoaderRoute: typeof VsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/': {
      id: '/scores/'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/': {
      id: '/merch/'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/': {
      id: '/judges/'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/': {
      id: '/fantasy/'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corps/': {
      id: '/corps/'
      path: '/corps'
      fullPath: '/corps'
      preLoaderRoute: typeof CorpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$slug': {
      id: '/vs/$slug'
      path: '/$slug'
      fullPath: '/vs/$slug'
      preLoaderRoute: typeof VsSlugRouteImport
      parentRoute: typeof VsRoute
    }
    '/staff/$personId': {
      id: '/staff/$personId'
      path: '/staff/$personId'
      fullPath: '/staff/$personId'
      preLoaderRoute: typeof StaffPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/stores': {
      id: '/shop/stores'
      path: '/shop/stores'
      fullPath: '/shop/stores'
      preLoaderRoute: typeof ShopStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bookmarks': {
      id: '/shop/bookmarks'
      path: '/shop/bookmarks'
      fullPath: '/shop/bookmarks'
      preLoaderRoute: typeof ShopBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/all': {
      id: '/shop/all'
      path: '/shop/all'
      fullPath: '/shop/all'
      preLoaderRoute: typeof ShopAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/$slug': {
      id: '/scores/$slug'
      path: '/scores/$slug'
      fullPath: '/scores/$slug'
      preLoaderRoute: typeof ScoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict/palette': {
      id: '/predict/palette'
      path: '/predict/palette'
      fullPath: '/predict/palette'
      preLoaderRoute: typeof PredictPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify/unsubscribe': {
      id: '/notify/unsubscribe'
      path: '/notify/unsubscribe'
      fullPath: '/notify/unsubscribe'
      preLoaderRoute: typeof NotifyUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/$': {
      id: '/merch/$'
      path: '/merch/$'
      fullPath: '/merch/$'
      preLoaderRoute: typeof MerchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/$judgeId': {
      id: '/judges/$judgeId'
      path: '/judges/$judgeId'
      fullPath: '/judges/$judgeId'
      preLoaderRoute: typeof JudgesJudgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/terms': {
      id: '/jobs/terms'
      path: '/jobs/terms'
      fullPath: '/jobs/terms'
      preLoaderRoute: typeof JobsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/talent': {
      id: '/jobs/talent'
      path: '/jobs/talent'
      fullPath: '/jobs/talent'
      preLoaderRoute: typeof JobsTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/privacy': {
      id: '/jobs/privacy'
      path: '/jobs/privacy'
      fullPath: '/jobs/privacy'
      preLoaderRoute: typeof JobsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/post': {
      id: '/jobs/post'
      path: '/jobs/post'
      fullPath: '/jobs/post'
      preLoaderRoute: typeof JobsPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/onboard': {
      id: '/jobs/onboard'
      path: '/jobs/onboard'
      fullPath: '/jobs/onboard'
      preLoaderRoute: typeof JobsOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/me': {
      id: '/jobs/me'
      path: '/jobs/me'
      fullPath: '/jobs/me'
      preLoaderRoute: typeof JobsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/guidelines': {
      id: '/jobs/guidelines'
      path: '/jobs/guidelines'
      fullPath: '/jobs/guidelines'
      preLoaderRoute: typeof JobsGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/categories': {
      id: '/jobs/categories'
      path: '/jobs/categories'
      fullPath: '/jobs/categories'
      preLoaderRoute: typeof JobsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/board': {
      id: '/jobs/board'
      path: '/jobs/board'
      fullPath: '/jobs/board'
      preLoaderRoute: typeof JobsBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/admin': {
      id: '/jobs/admin'
      path: '/jobs/admin'
      fullPath: '/jobs/admin'
      preLoaderRoute: typeof JobsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobSlug': {
      id: '/jobs/$jobSlug'
      path: '/jobs/$jobSlug'
      fullPath: '/jobs/$jobSlug'
      preLoaderRoute: typeof JobsJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/quiz-admin': {
      id: '/fantasy/quiz-admin'
      path: '/fantasy/quiz-admin'
      fullPath: '/fantasy/quiz-admin'
      preLoaderRoute: typeof FantasyQuizAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/create': {
      id: '/fantasy/create'
      path: '/fantasy/create'
      fullPath: '/fantasy/create'
      preLoaderRoute: typeof FantasyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/free-form-spike': {
      id: '/dev/free-form-spike'
      path: '/dev/free-form-spike'
      fullPath: '/dev/free-form-spike'
      preLoaderRoute: typeof DevFreeFormSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile-claims': {
      id: '/admin/profile-claims'
      path: '/admin/profile-claims'
      fullPath: '/admin/profile-claims'
      preLoaderRoute: typeof AdminProfileClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/identity': {
      id: '/admin/identity'
      path: '/admin/identity'
      fullPath: '/admin/identity'
      preLoaderRoute: typeof AdminIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/corps-colors': {
      id: '/admin/corps-colors'
      path: '/admin/corps-colors'
      fullPath: '/admin/corps-colors'
      preLoaderRoute: typeof AdminCorpsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/$slug/': {
      id: '/fantasy/$slug/'
      path: '/fantasy/$slug'
      fullPath: '/fantasy/$slug'
      preLoaderRoute: typeof FantasySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$yearSlug/': {
      id: '/events/$yearSlug/'
      path: '/events/$yearSlug'
      fullPath: '/events/$yearSlug'
      preLoaderRoute: typeof EventsYearSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$slug/$season': {
      id: '/shows/$slug/$season'
      path: '/shows/$slug/$season'
      fullPath: '/shows/$slug/$season'
      preLoaderRoute: typeof ShowsSlugSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/group/$storeId': {
      id: '/shop/group/$storeId'
      path: '/shop/group/$storeId'
      fullPath: '/shop/group/$storeId'
      preLoaderRoute: typeof ShopGroupStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/category/$cat': {
      id: '/shop/category/$cat'
      path: '/shop/category/$cat'
      fullPath: '/shop/category/$cat'
      preLoaderRoute: typeof ShopCategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/profile/$slug': {
      id: '/jobs/profile/$slug'
      path: '/jobs/profile/$slug'
      fullPath: '/jobs/profile/$slug'
      preLoaderRoute: typeof JobsProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/c/$slug': {
      id: '/jobs/c/$slug'
      path: '/jobs/c/$slug'
      fullPath: '/jobs/c/$slug'
      preLoaderRoute: typeof JobsCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/join/$token': {
      id: '/fantasy/join/$token'
      path: '/fantasy/join/$token'
      fullPath: '/fantasy/join/$token'
      preLoaderRoute: typeof FantasyJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/$slug/standings': {
      id: '/fantasy/$slug/standings'
      path: '/fantasy/$slug/standings'
      fullPath: '/fantasy/$slug/standings'
      preLoaderRoute: typeof FantasySlugStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/$slug/quiz': {
      id: '/fantasy/$slug/quiz'
      path: '/fantasy/$slug/quiz'
      fullPath: '/fantasy/$slug/quiz'
      preLoaderRoute: typeof FantasySlugQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy/$slug/draft': {
      id: '/fantasy/$slug/draft'
      path: '/fantasy/$slug/draft'
      fullPath: '/fantasy/$slug/draft'
      preLoaderRoute: typeof FantasySlugDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corps/$slug/{-$season}': {
      id: '/corps/$slug/{-$season}'
      path: '/corps/$slug/{-$season}'
      fullPath: '/corps/$slug/{-$season}'
      preLoaderRoute: typeof CorpsSlugChar123SeasonChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/fantasy/test-lab': {
      id: '/admin/fantasy/test-lab'
      path: '/admin/fantasy/test-lab'
      fullPath: '/admin/fantasy/test-lab'
      preLoaderRoute: typeof AdminFantasyTestLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fantasy/quiz': {
      id: '/admin/fantasy/quiz'
      path: '/admin/fantasy/quiz'
      fullPath: '/admin/fantasy/quiz'
      preLoaderRoute: typeof AdminFantasyQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fantasy/leagues': {
      id: '/admin/fantasy/leagues'
      path: '/admin/fantasy/leagues'
      fullPath: '/admin/fantasy/leagues'
      preLoaderRoute: typeof AdminFantasyLeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$yearSlug/$slug/prediction': {
      id: '/events/$yearSlug/$slug/prediction'
      path: '/events/$yearSlug/$slug/prediction'
      fullPath: '/events/$yearSlug/$slug/prediction'
      preLoaderRoute: typeof EventsYearSlugSlugPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/app-icon.svg': {
      id: '/app-icon.svg'
      path: '/app-icon.svg'
      fullPath: '/app-icon.svg'
      preLoaderRoute: typeof AppIconDotsvgServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/staff': {
      id: '/read-model/staff'
      path: '/read-model/staff'
      fullPath: '/read-model/staff'
      preLoaderRoute: typeof ReadModelStaffServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/manifest.json': {
      id: '/read-model/manifest.json'
      path: '/read-model/manifest.json'
      fullPath: '/read-model/manifest.json'
      preLoaderRoute: typeof ReadModelManifestDotjsonServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/judges': {
      id: '/read-model/judges'
      path: '/read-model/judges'
      fullPath: '/read-model/judges'
      preLoaderRoute: typeof ReadModelJudgesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/events': {
      id: '/read-model/events'
      path: '/read-model/events'
      fullPath: '/read-model/events'
      preLoaderRoute: typeof ReadModelEventsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/corps': {
      id: '/read-model/corps'
      path: '/read-model/corps'
      fullPath: '/read-model/corps'
      preLoaderRoute: typeof ReadModelCorpsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/collect': {
      id: '/api/collect'
      path: '/api/collect'
      fullPath: '/api/collect'
      preLoaderRoute: typeof ApiCollectServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/read-model/recaps/$slug': {
      id: '/read-model/recaps/$slug'
      path: '/read-model/recaps/$slug'
      fullPath: '/read-model/recaps/$slug'
      preLoaderRoute: typeof ReadModelRecapsSlugServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/show-media/$id': {
      id: '/api/show-media/$id'
      path: '/api/show-media/$id'
      fullPath: '/api/show-media/$id'
      preLoaderRoute: typeof ApiShowMediaIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/og/jobs-home': {
      id: '/api/og/jobs-home'
      path: '/api/og/jobs-home'
      fullPath: '/api/og/jobs-home'
      preLoaderRoute: typeof ApiOgJobsHomeServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/og/home': {
      id: '/api/og/home'
      path: '/api/og/home'
      fullPath: '/api/og/home'
      preLoaderRoute: typeof ApiOgHomeServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/jobs/stripe-webhook': {
      id: '/api/jobs/stripe-webhook'
      path: '/api/jobs/stripe-webhook'
      fullPath: '/api/jobs/stripe-webhook'
      preLoaderRoute: typeof ApiJobsStripeWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/fantasy/stripe-webhook': {
      id: '/api/fantasy/stripe-webhook'
      path: '/api/fantasy/stripe-webhook'
      fullPath: '/api/fantasy/stripe-webhook'
      preLoaderRoute: typeof ApiFantasyStripeWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/fantasy-media/$id': {
      id: '/api/fantasy-media/$id'
      path: '/api/fantasy-media/$id'
      fullPath: '/api/fantasy-media/$id'
      preLoaderRoute: typeof ApiFantasyMediaIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/og/score/$slug': {
      id: '/api/og/score/$slug'
      path: '/api/og/score/$slug'
      fullPath: '/api/og/score/$slug'
      preLoaderRoute: typeof ApiOgScoreSlugServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/fantasy/jobs/recompute': {
      id: '/api/fantasy/jobs/recompute'
      path: '/api/fantasy/jobs/recompute'
      fullPath: '/api/fantasy/jobs/recompute'
      preLoaderRoute: typeof ApiFantasyJobsRecomputeServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/fantasy/jobs/dispatch': {
      id: '/api/fantasy/jobs/dispatch'
      path: '/api/fantasy/jobs/dispatch'
      fullPath: '/api/fantasy/jobs/dispatch'
      preLoaderRoute: typeof ApiFantasyJobsDispatchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/og/show/$slug/$season': {
      id: '/api/og/show/$slug/$season'
      path: '/api/og/show/$slug/$season'
      fullPath: '/api/og/show/$slug/$season'
      preLoaderRoute: typeof ApiOgShowSlugSeasonServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/fantasy/draft/$leagueId/stream': {
      id: '/api/fantasy/draft/$leagueId/stream'
      path: '/api/fantasy/draft/$leagueId/stream'
      fullPath: '/api/fantasy/draft/$leagueId/stream'
      preLoaderRoute: typeof ApiFantasyDraftLeagueIdStreamServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface VsRouteChildren {
  VsSlugRoute: typeof VsSlugRoute
}

const VsRouteChildren: VsRouteChildren = {
  VsSlugRoute: VsSlugRoute,
}

const VsRouteWithChildren = VsRoute._addFileChildren(VsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RankingsRoute: RankingsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  VsRoute: VsRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCorpsColorsRoute: AdminCorpsColorsRoute,
  AdminIdentityRoute: AdminIdentityRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminProfileClaimsRoute: AdminProfileClaimsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  DevFreeFormSpikeRoute: DevFreeFormSpikeRoute,
  FantasyCreateRoute: FantasyCreateRoute,
  FantasyQuizAdminRoute: FantasyQuizAdminRoute,
  JobsJobSlugRoute: JobsJobSlugRoute,
  JobsAdminRoute: JobsAdminRoute,
  JobsBoardRoute: JobsBoardRoute,
  JobsCategoriesRoute: JobsCategoriesRoute,
  JobsGuidelinesRoute: JobsGuidelinesRoute,
  JobsMeRoute: JobsMeRoute,
  JobsOnboardRoute: JobsOnboardRoute,
  JobsPostRoute: JobsPostRoute,
  JobsPrivacyRoute: JobsPrivacyRoute,
  JobsTalentRoute: JobsTalentRoute,
  JobsTermsRoute: JobsTermsRoute,
  JudgesJudgeIdRoute: JudgesJudgeIdRoute,
  MerchSplatRoute: MerchSplatRoute,
  NotifyUnsubscribeRoute: NotifyUnsubscribeRoute,
  PredictPaletteRoute: PredictPaletteRoute,
  ScoresSlugRoute: ScoresSlugRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopAllRoute: ShopAllRoute,
  ShopBookmarksRoute: ShopBookmarksRoute,
  ShopCartRoute: ShopCartRoute,
  ShopStoresRoute: ShopStoresRoute,
  StaffPersonIdRoute: StaffPersonIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CorpsIndexRoute: CorpsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FantasyIndexRoute: FantasyIndexRoute,
  JudgesIndexRoute: JudgesIndexRoute,
  MerchIndexRoute: MerchIndexRoute,
  ScoresIndexRoute: ScoresIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShowsIndexRoute: ShowsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  AdminFantasyLeaguesRoute: AdminFantasyLeaguesRoute,
  AdminFantasyQuizRoute: AdminFantasyQuizRoute,
  AdminFantasyTestLabRoute: AdminFantasyTestLabRoute,
  CorpsSlugChar123SeasonChar125Route: CorpsSlugChar123SeasonChar125Route,
  FantasySlugDraftRoute: FantasySlugDraftRoute,
  FantasySlugQuizRoute: FantasySlugQuizRoute,
  FantasySlugStandingsRoute: FantasySlugStandingsRoute,
  FantasyJoinTokenRoute: FantasyJoinTokenRoute,
  JobsCSlugRoute: JobsCSlugRoute,
  JobsProfileSlugRoute: JobsProfileSlugRoute,
  ShopCategoryCatRoute: ShopCategoryCatRoute,
  ShopGroupStoreIdRoute: ShopGroupStoreIdRoute,
  ShowsSlugSeasonRoute: ShowsSlugSeasonRoute,
  EventsYearSlugIndexRoute: EventsYearSlugIndexRoute,
  FantasySlugIndexRoute: FantasySlugIndexRoute,
  EventsYearSlugSlugPredictionRoute: EventsYearSlugSlugPredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AppIconDotsvgServerRoute: AppIconDotsvgServerRoute,
  FaviconDoticoServerRoute: FaviconDoticoServerRoute,
  RobotsDottxtServerRoute: RobotsDottxtServerRoute,
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
  ApiCollectServerRoute: ApiCollectServerRoute,
  ApiMediaServerRoute: ApiMediaServerRoute,
  ApiVersionServerRoute: ApiVersionServerRoute,
  ReadModelCorpsServerRoute: ReadModelCorpsServerRoute,
  ReadModelEventsServerRoute: ReadModelEventsServerRoute,
  ReadModelJudgesServerRoute: ReadModelJudgesServerRoute,
  ReadModelManifestDotjsonServerRoute: ReadModelManifestDotjsonServerRoute,
  ReadModelStaffServerRoute: ReadModelStaffServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiFantasyMediaIdServerRoute: ApiFantasyMediaIdServerRoute,
  ApiFantasyStripeWebhookServerRoute: ApiFantasyStripeWebhookServerRoute,
  ApiJobsStripeWebhookServerRoute: ApiJobsStripeWebhookServerRoute,
  ApiOgHomeServerRoute: ApiOgHomeServerRoute,
  ApiOgJobsHomeServerRoute: ApiOgJobsHomeServerRoute,
  ApiShowMediaIdServerRoute: ApiShowMediaIdServerRoute,
  ReadModelRecapsSlugServerRoute: ReadModelRecapsSlugServerRoute,
  ApiFantasyJobsDispatchServerRoute: ApiFantasyJobsDispatchServerRoute,
  ApiFantasyJobsRecomputeServerRoute: ApiFantasyJobsRecomputeServerRoute,
  ApiOgScoreSlugServerRoute: ApiOgScoreSlugServerRoute,
  ApiFantasyDraftLeagueIdStreamServerRoute:
    ApiFantasyDraftLeagueIdStreamServerRoute,
  ApiOgShowSlugSeasonServerRoute: ApiOgShowSlugSeasonServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
