/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as MerchIndexRouteImport } from './routes/merch.index'
import { Route as JudgesIndexRouteImport } from './routes/judges/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CorpsIndexRouteImport } from './routes/corps/index'
import { Route as StaffPersonIdRouteImport } from './routes/staff/$personId'
import { Route as ShopStoresRouteImport } from './routes/shop/stores'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopBookmarksRouteImport } from './routes/shop/bookmarks'
import { Route as ShopAllRouteImport } from './routes/shop/all'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as MerchSplatRouteImport } from './routes/merch.$'
import { Route as JudgesJudgeIdRouteImport } from './routes/judges/$judgeId'
import { Route as DevFreeFormSpikeRouteImport } from './routes/dev/free-form-spike'
import { Route as AdminCorpsColorsRouteImport } from './routes/admin/corps-colors'
import { Route as EventsYearSlugIndexRouteImport } from './routes/events/$yearSlug/index'
import { Route as ShowsSlugSeasonRouteImport } from './routes/shows/$slug.$season'
import { Route as ShopGroupStoreIdRouteImport } from './routes/shop/group/$storeId'
import { Route as ShopCategoryCatRouteImport } from './routes/shop/category/$cat'
import { Route as CorpsSlugChar123SeasonChar125RouteImport } from './routes/corps/$slug.{-$season}'
import { Route as EventsYearSlugSlugPredictionRouteImport } from './routes/events/$yearSlug/$slug/prediction'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as RobotsDottxtServerRouteImport } from './routes/robots[.]txt'
import { ServerRoute as FaviconDoticoServerRouteImport } from './routes/favicon[.]ico'
import { ServerRoute as ApiMediaServerRouteImport } from './routes/api/media'

const rootServerRouteImport = createServerRootRoute()

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchIndexRoute = MerchIndexRouteImport.update({
  id: '/merch/',
  path: '/merch/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIndexRoute = JudgesIndexRouteImport.update({
  id: '/judges/',
  path: '/judges/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpsIndexRoute = CorpsIndexRouteImport.update({
  id: '/corps/',
  path: '/corps/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPersonIdRoute = StaffPersonIdRouteImport.update({
  id: '/staff/$personId',
  path: '/staff/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStoresRoute = ShopStoresRouteImport.update({
  id: '/shop/stores',
  path: '/shop/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBookmarksRoute = ShopBookmarksRouteImport.update({
  id: '/shop/bookmarks',
  path: '/shop/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAllRoute = ShopAllRouteImport.update({
  id: '/shop/all',
  path: '/shop/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchSplatRoute = MerchSplatRouteImport.update({
  id: '/merch/$',
  path: '/merch/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesJudgeIdRoute = JudgesJudgeIdRouteImport.update({
  id: '/judges/$judgeId',
  path: '/judges/$judgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFreeFormSpikeRoute = DevFreeFormSpikeRouteImport.update({
  id: '/dev/free-form-spike',
  path: '/dev/free-form-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorpsColorsRoute = AdminCorpsColorsRouteImport.update({
  id: '/admin/corps-colors',
  path: '/admin/corps-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsYearSlugIndexRoute = EventsYearSlugIndexRouteImport.update({
  id: '/events/$yearSlug/',
  path: '/events/$yearSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsSlugSeasonRoute = ShowsSlugSeasonRouteImport.update({
  id: '/shows/$slug/$season',
  path: '/shows/$slug/$season',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopGroupStoreIdRoute = ShopGroupStoreIdRouteImport.update({
  id: '/shop/group/$storeId',
  path: '/shop/group/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryCatRoute = ShopCategoryCatRouteImport.update({
  id: '/shop/category/$cat',
  path: '/shop/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpsSlugChar123SeasonChar125Route =
  CorpsSlugChar123SeasonChar125RouteImport.update({
    id: '/corps/$slug/{-$season}',
    path: '/corps/$slug/{-$season}',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsYearSlugSlugPredictionRoute =
  EventsYearSlugSlugPredictionRouteImport.update({
    id: '/events/$yearSlug/$slug/prediction',
    path: '/events/$yearSlug/$slug/prediction',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const RobotsDottxtServerRoute = RobotsDottxtServerRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootServerRouteImport,
} as any)
const FaviconDoticoServerRoute = FaviconDoticoServerRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMediaServerRoute = ApiMediaServerRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/corps': typeof CorpsIndexRoute
  '/events': typeof EventsIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/merch': typeof MerchIndexRoute
  '/shop': typeof ShopIndexRoute
  '/staff': typeof StaffIndexRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug': typeof EventsYearSlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/corps': typeof CorpsIndexRoute
  '/events': typeof EventsIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/merch': typeof MerchIndexRoute
  '/shop': typeof ShopIndexRoute
  '/staff': typeof StaffIndexRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug': typeof EventsYearSlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/corps-colors': typeof AdminCorpsColorsRoute
  '/dev/free-form-spike': typeof DevFreeFormSpikeRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/merch/$': typeof MerchSplatRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/all': typeof ShopAllRoute
  '/shop/bookmarks': typeof ShopBookmarksRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/stores': typeof ShopStoresRoute
  '/staff/$personId': typeof StaffPersonIdRoute
  '/corps/': typeof CorpsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/merch/': typeof MerchIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/corps/$slug/{-$season}': typeof CorpsSlugChar123SeasonChar125Route
  '/shop/category/$cat': typeof ShopCategoryCatRoute
  '/shop/group/$storeId': typeof ShopGroupStoreIdRoute
  '/shows/$slug/$season': typeof ShowsSlugSeasonRoute
  '/events/$yearSlug/': typeof EventsYearSlugIndexRoute
  '/events/$yearSlug/$slug/prediction': typeof EventsYearSlugSlugPredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/corps-colors'
    | '/dev/free-form-spike'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/corps'
    | '/events'
    | '/judges'
    | '/merch'
    | '/shop'
    | '/staff'
    | '/corps/$slug/{-$season}'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug'
    | '/events/$yearSlug/$slug/prediction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/corps-colors'
    | '/dev/free-form-spike'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/corps'
    | '/events'
    | '/judges'
    | '/merch'
    | '/shop'
    | '/staff'
    | '/corps/$slug/{-$season}'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug'
    | '/events/$yearSlug/$slug/prediction'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/corps-colors'
    | '/dev/free-form-spike'
    | '/judges/$judgeId'
    | '/merch/$'
    | '/shop/$productId'
    | '/shop/all'
    | '/shop/bookmarks'
    | '/shop/cart'
    | '/shop/stores'
    | '/staff/$personId'
    | '/corps/'
    | '/events/'
    | '/judges/'
    | '/merch/'
    | '/shop/'
    | '/staff/'
    | '/corps/$slug/{-$season}'
    | '/shop/category/$cat'
    | '/shop/group/$storeId'
    | '/shows/$slug/$season'
    | '/events/$yearSlug/'
    | '/events/$yearSlug/$slug/prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AdminCorpsColorsRoute: typeof AdminCorpsColorsRoute
  DevFreeFormSpikeRoute: typeof DevFreeFormSpikeRoute
  JudgesJudgeIdRoute: typeof JudgesJudgeIdRoute
  MerchSplatRoute: typeof MerchSplatRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopAllRoute: typeof ShopAllRoute
  ShopBookmarksRoute: typeof ShopBookmarksRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopStoresRoute: typeof ShopStoresRoute
  StaffPersonIdRoute: typeof StaffPersonIdRoute
  CorpsIndexRoute: typeof CorpsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JudgesIndexRoute: typeof JudgesIndexRoute
  MerchIndexRoute: typeof MerchIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  CorpsSlugChar123SeasonChar125Route: typeof CorpsSlugChar123SeasonChar125Route
  ShopCategoryCatRoute: typeof ShopCategoryCatRoute
  ShopGroupStoreIdRoute: typeof ShopGroupStoreIdRoute
  ShowsSlugSeasonRoute: typeof ShowsSlugSeasonRoute
  EventsYearSlugIndexRoute: typeof EventsYearSlugIndexRoute
  EventsYearSlugSlugPredictionRoute: typeof EventsYearSlugSlugPredictionRoute
}
export interface FileServerRoutesByFullPath {
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/media': typeof ApiMediaServerRoute
}
export interface FileServerRoutesByTo {
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/media': typeof ApiMediaServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/favicon.ico': typeof FaviconDoticoServerRoute
  '/robots.txt': typeof RobotsDottxtServerRoute
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/media': typeof ApiMediaServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/favicon.ico' | '/robots.txt' | '/sitemap.xml' | '/api/media'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/favicon.ico' | '/robots.txt' | '/sitemap.xml' | '/api/media'
  id:
    | '__root__'
    | '/favicon.ico'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/media'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  FaviconDoticoServerRoute: typeof FaviconDoticoServerRoute
  RobotsDottxtServerRoute: typeof RobotsDottxtServerRoute
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
  ApiMediaServerRoute: typeof ApiMediaServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/': {
      id: '/merch/'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/': {
      id: '/judges/'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corps/': {
      id: '/corps/'
      path: '/corps'
      fullPath: '/corps'
      preLoaderRoute: typeof CorpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$personId': {
      id: '/staff/$personId'
      path: '/staff/$personId'
      fullPath: '/staff/$personId'
      preLoaderRoute: typeof StaffPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/stores': {
      id: '/shop/stores'
      path: '/shop/stores'
      fullPath: '/shop/stores'
      preLoaderRoute: typeof ShopStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/shop/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bookmarks': {
      id: '/shop/bookmarks'
      path: '/shop/bookmarks'
      fullPath: '/shop/bookmarks'
      preLoaderRoute: typeof ShopBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/all': {
      id: '/shop/all'
      path: '/shop/all'
      fullPath: '/shop/all'
      preLoaderRoute: typeof ShopAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch/$': {
      id: '/merch/$'
      path: '/merch/$'
      fullPath: '/merch/$'
      preLoaderRoute: typeof MerchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/$judgeId': {
      id: '/judges/$judgeId'
      path: '/judges/$judgeId'
      fullPath: '/judges/$judgeId'
      preLoaderRoute: typeof JudgesJudgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/free-form-spike': {
      id: '/dev/free-form-spike'
      path: '/dev/free-form-spike'
      fullPath: '/dev/free-form-spike'
      preLoaderRoute: typeof DevFreeFormSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/corps-colors': {
      id: '/admin/corps-colors'
      path: '/admin/corps-colors'
      fullPath: '/admin/corps-colors'
      preLoaderRoute: typeof AdminCorpsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$yearSlug/': {
      id: '/events/$yearSlug/'
      path: '/events/$yearSlug'
      fullPath: '/events/$yearSlug'
      preLoaderRoute: typeof EventsYearSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$slug/$season': {
      id: '/shows/$slug/$season'
      path: '/shows/$slug/$season'
      fullPath: '/shows/$slug/$season'
      preLoaderRoute: typeof ShowsSlugSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/group/$storeId': {
      id: '/shop/group/$storeId'
      path: '/shop/group/$storeId'
      fullPath: '/shop/group/$storeId'
      preLoaderRoute: typeof ShopGroupStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/category/$cat': {
      id: '/shop/category/$cat'
      path: '/shop/category/$cat'
      fullPath: '/shop/category/$cat'
      preLoaderRoute: typeof ShopCategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corps/$slug/{-$season}': {
      id: '/corps/$slug/{-$season}'
      path: '/corps/$slug/{-$season}'
      fullPath: '/corps/$slug/{-$season}'
      preLoaderRoute: typeof CorpsSlugChar123SeasonChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$yearSlug/$slug/prediction': {
      id: '/events/$yearSlug/$slug/prediction'
      path: '/events/$yearSlug/$slug/prediction'
      fullPath: '/events/$yearSlug/$slug/prediction'
      preLoaderRoute: typeof EventsYearSlugSlugPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AdminCorpsColorsRoute: AdminCorpsColorsRoute,
  DevFreeFormSpikeRoute: DevFreeFormSpikeRoute,
  JudgesJudgeIdRoute: JudgesJudgeIdRoute,
  MerchSplatRoute: MerchSplatRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopAllRoute: ShopAllRoute,
  ShopBookmarksRoute: ShopBookmarksRoute,
  ShopCartRoute: ShopCartRoute,
  ShopStoresRoute: ShopStoresRoute,
  StaffPersonIdRoute: StaffPersonIdRoute,
  CorpsIndexRoute: CorpsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JudgesIndexRoute: JudgesIndexRoute,
  MerchIndexRoute: MerchIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  CorpsSlugChar123SeasonChar125Route: CorpsSlugChar123SeasonChar125Route,
  ShopCategoryCatRoute: ShopCategoryCatRoute,
  ShopGroupStoreIdRoute: ShopGroupStoreIdRoute,
  ShowsSlugSeasonRoute: ShowsSlugSeasonRoute,
  EventsYearSlugIndexRoute: EventsYearSlugIndexRoute,
  EventsYearSlugSlugPredictionRoute: EventsYearSlugSlugPredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  FaviconDoticoServerRoute: FaviconDoticoServerRoute,
  RobotsDottxtServerRoute: RobotsDottxtServerRoute,
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
  ApiMediaServerRoute: ApiMediaServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
