// @generated by @nkzw/fate/vite
import type { Event, fate as fateServer } from '../server.ts';
import { clientRoot, createClient, createHTTPTransport, mutation, type InferFateAPI } from 'react-fate';


type FateAPI = InferFateAPI<typeof fateServer>;

const mutations = {

} as const;

const roots = {
  'event': clientRoot<Array<Event>, 'Event'>('Event'),
  'events': clientRoot<FateAPI['lists']['events']['output'], 'Event'>('Event'),
} as const;

export type GeneratedClientMutations = typeof mutations;
export type GeneratedClientRoots = typeof roots;
const hydrationScope = "{\"moduleName\":\"../server.ts\",\"roots\":{\"events\":{\"kind\":\"list\",\"procedure\":\"list\",\"router\":\"event\",\"type\":\"Event\"}},\"types\":[{\"type\":\"Event\"}]}" as const;

export const createFateClient = (options: {
  fetch?: typeof fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
  liveRetryMs?: number;
  liveUrl?: string | URL;
  onLiveError?: (error: unknown) => void;
  url: string | URL;
}) =>
  createClient<[GeneratedClientRoots, GeneratedClientMutations], typeof hydrationScope>({
    hydrationScope,
    mutations,
    onLiveError: options.onLiveError,
    roots,
    transport: createHTTPTransport<FateAPI>({
      fetch: options.fetch,
      headers: options.headers,
      live: true,
      liveRetryMs: options.liveRetryMs,
      liveUrl: options.liveUrl,
      url: options.url,
    }),
    types: [
        {
          type: 'Event',
        },
      ],
  });

type GeneratedCreateFateClient = typeof createFateClient;

declare module 'react-fate/client' {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}

  export function createFateClient(
    ...args: Parameters<GeneratedCreateFateClient>
  ): ReturnType<GeneratedCreateFateClient>;
}

